#!/usr/bin/env python3
"""
╔═══════════════════════════════════════════════════════════════════════════════╗
║   ██████╗ █████╗ ████████╗███████╗    ██████╗  ██████╗ ██╗  ██╗███████╗       ║
║  ██╔════╝██╔══██╗╚══██╔══╝██╔════╝    ██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝       ║
║  ██║     ███████║   ██║   ███████╗    ██████╔╝██║   ██║█████╔╝ █████╗         ║
║  ██║     ██╔══██║   ██║   ╚════██║    ██╔═══╝ ██║   ██║██╔═██╗ ██╔══╝         ║
║  ╚██████╗██║  ██║   ██║   ███████║    ██║     ╚██████╔╝██║  ██╗███████╗       ║
║   ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝    ╚═╝      ╚═════╝ ╚═╝  ╚═╝╚══════╝       ║
║                             RED VERSION 0.1                                    ║
║                      Team Flames / Cat OS / Samsoft                           ║
║═══════════════════════════════════════════════════════════════════════════════║
║  COMPLETE POKEMON RED ENGINE - ALL 151 - ALL KANTO - FULL SAVE SYSTEM         ║
╚═══════════════════════════════════════════════════════════════════════════════╝

Controls:
  Arrow Keys - Move / Navigate menus
  Z / Space  - Confirm / A button
  X / Esc    - Cancel / B button  
  Enter      - Start menu
  
Save Location: ~/.cats_pokered_save.json
"""

import pygame
import random
import math
import json
import os
import hashlib
import array
from datetime import datetime

pygame.init()
pygame.mixer.init(frequency=22050, size=-16, channels=2, buffer=512)

# ═══════════════════════════════════════════════════════════════════════════════
# DISPLAY
# ═══════════════════════════════════════════════════════════════════════════════
GB_W, GB_H = 160, 144
SCALE = 4
WIDTH, HEIGHT = GB_W * SCALE, GB_H * SCALE
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Cat's PokeRed 0.1")
clock = pygame.time.Clock()
gb = pygame.Surface((GB_W, GB_H))

# ═══════════════════════════════════════════════════════════════════════════════
# COLORS
# ═══════════════════════════════════════════════════════════════════════════════
WHITE = (248, 248, 248)
LIGHT = (168, 184, 168)
DARK = (88, 104, 88)
BLACK = (8, 24, 8)
RED = (248, 88, 88)
BLUE = (104, 144, 248)
GREEN = (120, 200, 80)
YELLOW = (248, 208, 48)
PURPLE = (160, 88, 200)
BROWN = (176, 128, 80)
PINK = (248, 176, 200)
GRAY = (168, 168, 168)
ORANGE = (248, 168, 88)
CYAN = (128, 216, 216)

TYPE_COLORS = {
    'NORMAL': (168,168,120), 'FIRE': (240,128,48), 'WATER': (104,144,240),
    'ELECTRIC': (248,208,48), 'GRASS': (120,200,80), 'ICE': (152,216,216),
    'FIGHTING': (192,48,40), 'POISON': (160,64,160), 'GROUND': (224,192,104),
    'FLYING': (168,144,240), 'PSYCHIC': (248,88,136), 'BUG': (168,184,32),
    'ROCK': (184,160,56), 'GHOST': (112,88,152), 'DRAGON': (112,56,248),
}

# ═══════════════════════════════════════════════════════════════════════════════
# TYPE CHART
# ═══════════════════════════════════════════════════════════════════════════════
TYPE_CHART = {}
for a, ds in [('FIRE',['GRASS','ICE','BUG']),('WATER',['FIRE','GROUND','ROCK']),
    ('ELECTRIC',['WATER','FLYING']),('GRASS',['WATER','GROUND','ROCK']),
    ('ICE',['GRASS','GROUND','FLYING','DRAGON']),('FIGHTING',['NORMAL','ICE','ROCK']),
    ('POISON',['GRASS','BUG']),('GROUND',['FIRE','ELECTRIC','POISON','ROCK']),
    ('FLYING',['GRASS','FIGHTING','BUG']),('PSYCHIC',['FIGHTING','POISON']),
    ('BUG',['GRASS','POISON','PSYCHIC']),('ROCK',['FIRE','ICE','FLYING','BUG']),
    ('GHOST',['PSYCHIC','GHOST']),('DRAGON',['DRAGON'])]:
    for d in ds: TYPE_CHART[(a,d)] = 2.0
for a, ds in [('FIRE',['FIRE','WATER','ROCK','DRAGON']),('WATER',['WATER','GRASS','DRAGON']),
    ('ELECTRIC',['ELECTRIC','GRASS','DRAGON']),('GRASS',['FIRE','GRASS','POISON','FLYING','BUG','DRAGON']),
    ('ICE',['FIRE','WATER','ICE']),('FIGHTING',['POISON','FLYING','PSYCHIC','BUG']),
    ('POISON',['POISON','GROUND','ROCK','GHOST']),('GROUND',['GRASS','BUG']),
    ('FLYING',['ELECTRIC','ROCK']),('PSYCHIC',['PSYCHIC']),
    ('BUG',['FIRE','FIGHTING','FLYING','GHOST']),('ROCK',['FIGHTING','GROUND']),
    ('NORMAL',['ROCK'])]:
    for d in ds: TYPE_CHART[(a,d)] = 0.5
for a, ds in [('NORMAL',['GHOST']),('ELECTRIC',['GROUND']),('FIGHTING',['GHOST']),
    ('GROUND',['FLYING']),('GHOST',['NORMAL'])]:
    for d in ds: TYPE_CHART[(a,d)] = 0.0

def type_eff(atk_type, def_types):
    m = 1.0
    for t in def_types: m *= TYPE_CHART.get((atk_type, t), 1.0)
    return m

# ═══════════════════════════════════════════════════════════════════════════════
# MOVES DATABASE
# ═══════════════════════════════════════════════════════════════════════════════
MOVES = {
    'TACKLE':('NORMAL',40,100,35,'PHY',None),'SCRATCH':('NORMAL',40,100,35,'PHY',None),
    'POUND':('NORMAL',40,100,35,'PHY',None),'QUICK ATTACK':('NORMAL',40,100,30,'PHY','PRI'),
    'SLAM':('NORMAL',80,75,20,'PHY',None),'HEADBUTT':('NORMAL',70,100,15,'PHY','FLN30'),
    'BODY SLAM':('NORMAL',85,100,15,'PHY','PAR30'),'TAKE DOWN':('NORMAL',90,85,20,'PHY','RCL25'),
    'DOUBLE-EDGE':('NORMAL',120,100,15,'PHY','RCL33'),'HYPER BEAM':('NORMAL',150,90,5,'SPC','RECH'),
    'WRAP':('NORMAL',15,90,20,'PHY','BIND'),'MEGA PUNCH':('NORMAL',80,85,20,'PHY',None),
    'MEGA KICK':('NORMAL',120,75,5,'PHY',None),'FURY ATTACK':('NORMAL',15,85,20,'PHY','MULTI'),
    'RAGE':('NORMAL',20,100,20,'PHY',None),'THRASH':('NORMAL',120,100,10,'PHY','RAMP'),
    'CUT':('NORMAL',50,95,30,'PHY',None),'STRENGTH':('NORMAL',80,100,15,'PHY',None),
    'SWIFT':('NORMAL',60,999,20,'SPC',None),'SLASH':('NORMAL',70,100,20,'PHY','CRIT'),
    'VICE GRIP':('NORMAL',55,100,30,'PHY',None),'GUILLOTINE':('NORMAL',0,30,5,'PHY','OHKO'),
    'HORN ATTACK':('NORMAL',65,100,25,'PHY',None),'HORN DRILL':('NORMAL',0,30,5,'PHY','OHKO'),
    'HYPER FANG':('NORMAL',80,90,15,'PHY','FLN10'),'TRI ATTACK':('NORMAL',80,100,10,'SPC',None),
    'PAY DAY':('NORMAL',40,100,20,'PHY','PAY'),'SELFDESTRUCT':('NORMAL',200,100,5,'PHY','SELF'),
    'EXPLOSION':('NORMAL',250,100,5,'PHY','SELF'),
    'GROWL':('NORMAL',0,100,40,'STA','ATK-'),'TAIL WHIP':('NORMAL',0,100,30,'STA','DEF-'),
    'LEER':('NORMAL',0,100,30,'STA','DEF-'),'SCREECH':('NORMAL',0,85,40,'STA','DEF--'),
    'DEFENSE CURL':('NORMAL',0,100,40,'STA','DEF+'),'HARDEN':('NORMAL',0,100,30,'STA','DEF+'),
    'SWORDS DANCE':('NORMAL',0,100,20,'STA','ATK++'),'FOCUS ENERGY':('NORMAL',0,100,30,'STA','FOCUS'),
    'GROWTH':('NORMAL',0,100,20,'STA','SPA+'),'DOUBLE TEAM':('NORMAL',0,100,15,'STA','EVA+'),
    'MINIMIZE':('NORMAL',0,100,10,'STA','EVA++'),'RECOVER':('NORMAL',0,100,10,'STA','HEAL50'),
    'SOFTBOILED':('NORMAL',0,100,10,'STA','HEAL50'),'REST':('PSYCHIC',0,100,10,'STA','REST'),
    'SUBSTITUTE':('NORMAL',0,100,10,'STA','SUB'),'METRONOME':('NORMAL',0,100,10,'STA','RAND'),
    'TRANSFORM':('NORMAL',0,100,10,'STA','TFORM'),'SPLASH':('NORMAL',0,100,40,'STA',None),
    'ROAR':('NORMAL',0,100,20,'STA','FLEE'),'DISABLE':('NORMAL',0,100,20,'STA','DIS'),
    'GLARE':('NORMAL',0,100,30,'STA','PAR'),'SUPERSONIC':('NORMAL',0,55,20,'STA','CONF'),
    'CONFUSE RAY':('GHOST',0,100,10,'STA','CONF'),'LIGHT SCREEN':('PSYCHIC',0,100,30,'STA','LSCR'),
    'REFLECT':('PSYCHIC',0,100,20,'STA','REFL'),'HAZE':('ICE',0,100,30,'STA','HAZE'),
    'FLASH':('NORMAL',0,100,20,'STA','ACC-'),'SAND ATTACK':('GROUND',0,100,15,'STA','ACC-'),
    'SMOKESCREEN':('NORMAL',0,100,20,'STA','ACC-'),'MEDITATE':('PSYCHIC',0,100,40,'STA','ATK+'),
    'EMBER':('FIRE',40,100,25,'SPC','BRN10'),'FLAMETHROWER':('FIRE',90,100,15,'SPC','BRN10'),
    'FIRE BLAST':('FIRE',110,85,5,'SPC','BRN10'),'FIRE SPIN':('FIRE',35,85,15,'SPC','BIND'),
    'FIRE PUNCH':('FIRE',75,100,15,'PHY','BRN10'),
    'BUBBLE':('WATER',40,100,30,'SPC','SPD-10'),'WATER GUN':('WATER',40,100,25,'SPC',None),
    'HYDRO PUMP':('WATER',110,80,5,'SPC',None),'SURF':('WATER',90,100,15,'SPC',None),
    'BUBBLEBEAM':('WATER',65,100,20,'SPC','SPD-10'),'WATERFALL':('WATER',80,100,15,'PHY',None),
    'CLAMP':('WATER',35,85,15,'PHY','BIND'),'CRABHAMMER':('WATER',100,90,10,'PHY','CRIT'),
    'WITHDRAW':('WATER',0,100,40,'STA','DEF+'),
    'THUNDERSHOCK':('ELECTRIC',40,100,30,'SPC','PAR10'),'THUNDERBOLT':('ELECTRIC',90,100,15,'SPC','PAR10'),
    'THUNDER':('ELECTRIC',110,70,10,'SPC','PAR30'),'THUNDER WAVE':('ELECTRIC',0,90,20,'STA','PAR'),
    'THUNDER PUNCH':('ELECTRIC',75,100,15,'PHY','PAR10'),
    'VINE WHIP':('GRASS',45,100,25,'PHY',None),'RAZOR LEAF':('GRASS',55,95,25,'PHY','CRIT'),
    'SOLAR BEAM':('GRASS',120,100,10,'SPC','CHRG'),'ABSORB':('GRASS',20,100,25,'SPC','DRN'),
    'MEGA DRAIN':('GRASS',40,100,15,'SPC','DRN'),'LEECH SEED':('GRASS',0,90,10,'STA','LSED'),
    'SLEEP POWDER':('GRASS',0,75,15,'STA','SLP'),'STUN SPORE':('GRASS',0,75,30,'STA','PAR'),
    'POISON POWDER':('POISON',0,75,35,'STA','PSN'),'SPORE':('GRASS',0,100,15,'STA','SLP'),
    'PETAL DANCE':('GRASS',120,100,10,'SPC','RAMP'),
    'ICE BEAM':('ICE',90,100,10,'SPC','FRZ10'),'BLIZZARD':('ICE',110,70,5,'SPC','FRZ10'),
    'ICE PUNCH':('ICE',75,100,15,'PHY','FRZ10'),'AURORA BEAM':('ICE',65,100,20,'SPC','ATK-10'),
    'MIST':('ICE',0,100,30,'STA','MIST'),
    'KARATE CHOP':('FIGHTING',50,100,25,'PHY','CRIT'),'LOW KICK':('FIGHTING',50,90,20,'PHY','FLN30'),
    'DOUBLE KICK':('FIGHTING',30,100,30,'PHY','x2'),'JUMP KICK':('FIGHTING',100,95,10,'PHY','CRASH'),
    'HI JUMP KICK':('FIGHTING',130,90,10,'PHY','CRASH'),'ROLLING KICK':('FIGHTING',60,85,15,'PHY','FLN30'),
    'SUBMISSION':('FIGHTING',80,80,20,'PHY','RCL25'),'SEISMIC TOSS':('FIGHTING',0,100,20,'PHY','LVLDMG'),
    'COUNTER':('FIGHTING',0,100,20,'PHY','CNTR'),
    'POISON STING':('POISON',15,100,35,'PHY','PSN30'),'SLUDGE':('POISON',65,100,20,'SPC','PSN30'),
    'SMOG':('POISON',30,70,20,'SPC','PSN40'),'ACID':('POISON',40,100,30,'SPC','DEF-10'),
    'POISON GAS':('POISON',0,90,40,'STA','PSN'),'TOXIC':('POISON',0,90,10,'STA','TXC'),
    'ACID ARMOR':('POISON',0,100,20,'STA','DEF++'),'TWINEEDLE':('BUG',25,100,20,'PHY','x2PSN'),
    'EARTHQUAKE':('GROUND',100,100,10,'PHY',None),'DIG':('GROUND',80,100,10,'PHY','DIG'),
    'FISSURE':('GROUND',0,30,5,'PHY','OHKO'),'BONE CLUB':('GROUND',65,85,20,'PHY','FLN10'),
    'BONEMERANG':('GROUND',50,90,10,'PHY','x2'),
    'PECK':('FLYING',35,100,35,'PHY',None),'DRILL PECK':('FLYING',80,100,20,'PHY',None),
    'FLY':('FLYING',90,95,15,'PHY','FLY'),'WING ATTACK':('FLYING',60,100,35,'PHY',None),
    'GUST':('FLYING',40,100,35,'SPC',None),'SKY ATTACK':('FLYING',140,90,5,'PHY','CHRG'),
    'MIRROR MOVE':('FLYING',0,100,20,'STA','MIRR'),
    'CONFUSION':('PSYCHIC',50,100,25,'SPC','CNF10'),'PSYBEAM':('PSYCHIC',65,100,20,'SPC','CNF10'),
    'PSYCHIC':('PSYCHIC',90,100,10,'SPC','SPD-10'),'PSYWAVE':('PSYCHIC',0,100,15,'SPC','RDMG'),
    'HYPNOSIS':('PSYCHIC',0,60,20,'STA','SLP'),'DREAM EATER':('PSYCHIC',100,100,15,'SPC','DREAT'),
    'TELEPORT':('PSYCHIC',0,100,20,'STA','FLEE'),'AGILITY':('PSYCHIC',0,100,30,'STA','SPD++'),
    'AMNESIA':('PSYCHIC',0,100,20,'STA','SPD++'),'BARRIER':('PSYCHIC',0,100,20,'STA','DEF++'),
    'STRING SHOT':('BUG',0,95,40,'STA','SPD-'),'LEECH LIFE':('BUG',80,100,10,'PHY','DRN'),
    'PIN MISSILE':('BUG',25,95,20,'PHY','MULTI'),
    'ROCK THROW':('ROCK',50,90,15,'PHY',None),'ROCK SLIDE':('ROCK',75,90,10,'PHY','FLN30'),
    'LICK':('GHOST',30,100,30,'PHY','PAR30'),'NIGHT SHADE':('GHOST',0,100,15,'SPC','LVLDMG'),
    'DRAGON RAGE':('DRAGON',0,100,10,'SPC','FIX40'),
    'SING':('NORMAL',0,55,15,'STA','SLP'),'LOVELY KISS':('NORMAL',0,75,10,'STA','SLP'),
    'BITE':('NORMAL',60,100,25,'PHY','FLN30'),'SONIC BOOM':('NORMAL',0,90,20,'SPC','FIX20'),
    'BIND':('NORMAL',15,85,20,'PHY','BIND'),'COMET PUNCH':('NORMAL',18,85,15,'PHY','MULTI'),
    'FURY SWIPES':('NORMAL',18,80,15,'PHY','MULTI'),'STOMP':('NORMAL',65,100,20,'PHY','FLN30'),
    'DOUBLE SLAP':('NORMAL',15,85,10,'PHY','MULTI'),'CONSTRICT':('NORMAL',10,100,35,'PHY','SPD-10'),
    'BARRAGE':('NORMAL',15,85,20,'PHY','MULTI'),'SPIKE CANNON':('NORMAL',20,100,15,'PHY','MULTI'),
    'SUPER FANG':('NORMAL',0,90,10,'PHY','HALF'),'DIZZY PUNCH':('NORMAL',70,100,10,'PHY','CNF20'),
    'SKULL BASH':('NORMAL',130,100,10,'PHY','CHRG'),
    'SHARPEN':('NORMAL',0,100,30,'STA','ATK+'),'EGG BOMB':('NORMAL',100,75,10,'PHY',None),
}

# ═══════════════════════════════════════════════════════════════════════════════
# ALL 151 POKEMON
# ═══════════════════════════════════════════════════════════════════════════════
# (name, [types], [HP,ATK,DEF,SPA,SPD,SPE], base_exp, catch_rate, evo_lvl, evo_to, {lvl:[moves]})
POKEMON = {
    1:('BULBASAUR',['GRASS','POISON'],[45,49,49,65,65,45],64,45,16,2,{1:['TACKLE','GROWL'],7:['LEECH SEED'],13:['VINE WHIP'],20:['POISON POWDER','SLEEP POWDER'],27:['RAZOR LEAF'],34:['GROWTH'],41:['SOLAR BEAM']}),
    2:('IVYSAUR',['GRASS','POISON'],[60,62,63,80,80,60],142,45,32,3,{1:['TACKLE','GROWL','LEECH SEED'],13:['VINE WHIP'],22:['POISON POWDER','SLEEP POWDER'],30:['RAZOR LEAF'],38:['GROWTH'],46:['SOLAR BEAM']}),
    3:('VENUSAUR',['GRASS','POISON'],[80,82,83,100,100,80],236,45,None,None,{1:['TACKLE','GROWL','LEECH SEED','VINE WHIP'],22:['POISON POWDER'],30:['RAZOR LEAF'],43:['GROWTH'],55:['SOLAR BEAM']}),
    4:('CHARMANDER',['FIRE'],[39,52,43,60,50,65],62,45,16,5,{1:['SCRATCH','GROWL'],9:['EMBER'],15:['LEER'],22:['RAGE'],30:['SLASH'],38:['FLAMETHROWER'],46:['FIRE SPIN']}),
    5:('CHARMELEON',['FIRE'],[58,64,58,80,65,80],142,45,36,6,{1:['SCRATCH','GROWL','EMBER'],15:['LEER'],24:['RAGE'],33:['SLASH'],42:['FLAMETHROWER'],56:['FIRE SPIN']}),
    6:('CHARIZARD',['FIRE','FLYING'],[78,84,78,109,85,100],240,45,None,None,{1:['SCRATCH','GROWL','EMBER','LEER'],24:['RAGE'],36:['SLASH'],46:['FLAMETHROWER'],55:['FIRE SPIN']}),
    7:('SQUIRTLE',['WATER'],[44,48,65,50,64,43],63,45,16,8,{1:['TACKLE','TAIL WHIP'],8:['BUBBLE'],15:['WATER GUN'],22:['BITE'],28:['WITHDRAW'],35:['SKULL BASH'],42:['HYDRO PUMP']}),
    8:('WARTORTLE',['WATER'],[59,63,80,65,80,58],143,45,36,9,{1:['TACKLE','TAIL WHIP','BUBBLE'],15:['WATER GUN'],24:['BITE'],31:['WITHDRAW'],39:['SKULL BASH'],47:['HYDRO PUMP']}),
    9:('BLASTOISE',['WATER'],[79,83,100,85,105,78],239,45,None,None,{1:['TACKLE','TAIL WHIP','BUBBLE','WATER GUN'],24:['BITE'],31:['WITHDRAW'],42:['SKULL BASH'],52:['HYDRO PUMP']}),
    10:('CATERPIE',['BUG'],[45,30,35,20,20,45],53,255,7,11,{1:['TACKLE','STRING SHOT']}),
    11:('METAPOD',['BUG'],[50,20,55,25,25,30],72,120,10,12,{1:['HARDEN']}),
    12:('BUTTERFREE',['BUG','FLYING'],[60,45,50,90,80,70],178,45,None,None,{1:['CONFUSION'],12:['CONFUSION'],15:['POISON POWDER'],16:['STUN SPORE'],17:['SLEEP POWDER'],21:['SUPERSONIC'],26:['PSYBEAM']}),
    13:('WEEDLE',['BUG','POISON'],[40,35,30,20,20,50],52,255,7,14,{1:['POISON STING','STRING SHOT']}),
    14:('KAKUNA',['BUG','POISON'],[45,25,50,25,25,35],71,120,10,15,{1:['HARDEN']}),
    15:('BEEDRILL',['BUG','POISON'],[65,90,40,45,80,75],178,45,None,None,{1:['FURY ATTACK'],12:['FURY ATTACK'],16:['FOCUS ENERGY'],20:['TWINEEDLE'],25:['RAGE'],30:['PIN MISSILE'],35:['AGILITY']}),
    16:('PIDGEY',['NORMAL','FLYING'],[40,45,40,35,35,56],55,255,18,17,{1:['GUST'],5:['SAND ATTACK'],12:['QUICK ATTACK'],19:['WING ATTACK'],28:['AGILITY'],36:['MIRROR MOVE']}),
    17:('PIDGEOTTO',['NORMAL','FLYING'],[63,60,55,50,50,71],113,120,36,18,{1:['GUST','SAND ATTACK'],12:['QUICK ATTACK'],21:['WING ATTACK'],31:['AGILITY'],40:['MIRROR MOVE']}),
    18:('PIDGEOT',['NORMAL','FLYING'],[83,80,75,70,70,101],172,45,None,None,{1:['GUST','SAND ATTACK','QUICK ATTACK'],21:['WING ATTACK'],31:['AGILITY'],44:['MIRROR MOVE']}),
    19:('RATTATA',['NORMAL'],[30,56,35,25,35,72],57,255,20,20,{1:['TACKLE','TAIL WHIP'],7:['QUICK ATTACK'],14:['HYPER FANG'],23:['FOCUS ENERGY'],34:['SUPER FANG']}),
    20:('RATICATE',['NORMAL'],[55,81,60,50,70,97],116,127,None,None,{1:['TACKLE','TAIL WHIP','QUICK ATTACK'],14:['HYPER FANG'],27:['FOCUS ENERGY'],41:['SUPER FANG']}),
    21:('SPEAROW',['NORMAL','FLYING'],[40,60,30,31,31,70],58,255,20,22,{1:['PECK','GROWL'],9:['LEER'],15:['FURY ATTACK'],22:['MIRROR MOVE'],29:['DRILL PECK'],36:['AGILITY']}),
    22:('FEAROW',['NORMAL','FLYING'],[65,90,65,61,61,100],162,90,None,None,{1:['PECK','GROWL','LEER'],15:['FURY ATTACK'],25:['MIRROR MOVE'],34:['DRILL PECK'],43:['AGILITY']}),
    23:('EKANS',['POISON'],[35,60,44,40,54,55],62,255,22,24,{1:['WRAP','LEER'],10:['POISON STING'],17:['BITE'],24:['GLARE'],31:['SCREECH'],38:['ACID']}),
    24:('ARBOK',['POISON'],[60,95,69,65,79,80],147,90,None,None,{1:['WRAP','LEER','POISON STING'],17:['BITE'],27:['GLARE'],36:['SCREECH'],47:['ACID']}),
    25:('PIKACHU',['ELECTRIC'],[35,55,40,50,50,90],112,190,None,26,{1:['THUNDERSHOCK','GROWL'],9:['THUNDER WAVE'],16:['QUICK ATTACK'],26:['SWIFT'],33:['AGILITY'],43:['THUNDER']}),
    26:('RAICHU',['ELECTRIC'],[60,90,55,90,80,110],218,75,None,None,{1:['THUNDERSHOCK','GROWL','THUNDER WAVE']}),
    27:('SANDSHREW',['GROUND'],[50,75,85,20,30,40],93,255,22,28,{1:['SCRATCH'],10:['SAND ATTACK'],17:['SLASH'],24:['POISON STING'],31:['SWIFT'],38:['FURY SWIPES']}),
    28:('SANDSLASH',['GROUND'],[75,100,110,45,55,65],163,90,None,None,{1:['SCRATCH','SAND ATTACK'],17:['SLASH'],27:['POISON STING'],36:['SWIFT'],47:['FURY SWIPES']}),
    29:('NIDORAN♀',['POISON'],[55,47,52,40,40,41],59,235,16,30,{1:['GROWL','TACKLE'],8:['SCRATCH'],14:['POISON STING'],21:['TAIL WHIP'],29:['BITE'],36:['FURY SWIPES'],43:['DOUBLE KICK']}),
    30:('NIDORINA',['POISON'],[70,62,67,55,55,56],117,120,None,31,{1:['GROWL','TACKLE','SCRATCH'],14:['POISON STING'],23:['TAIL WHIP'],32:['BITE'],41:['FURY SWIPES'],50:['DOUBLE KICK']}),
    31:('NIDOQUEEN',['POISON','GROUND'],[90,92,87,75,85,76],194,45,None,None,{1:['TACKLE','SCRATCH','TAIL WHIP','BODY SLAM']}),
    32:('NIDORAN♂',['POISON'],[46,57,40,40,40,50],60,235,16,33,{1:['LEER','TACKLE'],8:['HORN ATTACK'],14:['POISON STING'],21:['FOCUS ENERGY'],29:['FURY ATTACK'],36:['HORN DRILL'],43:['DOUBLE KICK']}),
    33:('NIDORINO',['POISON'],[61,72,57,55,55,65],118,120,None,34,{1:['LEER','TACKLE','HORN ATTACK'],14:['POISON STING'],23:['FOCUS ENERGY'],32:['FURY ATTACK'],41:['HORN DRILL'],50:['DOUBLE KICK']}),
    34:('NIDOKING',['POISON','GROUND'],[81,102,77,85,75,85],195,45,None,None,{1:['TACKLE','HORN ATTACK','POISON STING','THRASH']}),
    35:('CLEFAIRY',['NORMAL'],[70,45,48,60,65,35],68,150,None,36,{1:['POUND','GROWL'],13:['SING'],18:['DOUBLE SLAP'],24:['MINIMIZE'],31:['METRONOME'],39:['DEFENSE CURL'],48:['LIGHT SCREEN']}),
    36:('CLEFABLE',['NORMAL'],[95,70,73,95,90,60],129,25,None,None,{1:['SING','DOUBLE SLAP','MINIMIZE','METRONOME']}),
    37:('VULPIX',['FIRE'],[38,41,40,50,65,65],63,190,None,38,{1:['EMBER','TAIL WHIP'],16:['QUICK ATTACK'],21:['ROAR'],28:['CONFUSE RAY'],35:['FLAMETHROWER'],42:['FIRE SPIN']}),
    38:('NINETALES',['FIRE'],[73,76,75,81,100,100],178,75,None,None,{1:['EMBER','TAIL WHIP','QUICK ATTACK','CONFUSE RAY']}),
    39:('JIGGLYPUFF',['NORMAL'],[115,45,20,45,25,20],76,170,None,40,{1:['SING'],9:['POUND'],14:['DEFENSE CURL'],19:['DOUBLE SLAP'],24:['REST'],29:['BODY SLAM'],34:['DOUBLE-EDGE']}),
    40:('WIGGLYTUFF',['NORMAL'],[140,70,45,85,50,45],109,50,None,None,{1:['SING','DOUBLE SLAP','DEFENSE CURL','DOUBLE-EDGE']}),
    41:('ZUBAT',['POISON','FLYING'],[40,45,35,30,40,55],54,255,22,42,{1:['LEECH LIFE'],10:['SUPERSONIC'],15:['BITE'],21:['CONFUSE RAY'],28:['WING ATTACK'],36:['HAZE']}),
    42:('GOLBAT',['POISON','FLYING'],[75,80,70,65,75,90],171,90,None,None,{1:['LEECH LIFE','SCREECH','BITE'],21:['CONFUSE RAY'],32:['WING ATTACK'],43:['HAZE']}),
    43:('ODDISH',['GRASS','POISON'],[45,50,55,75,65,30],78,255,21,44,{1:['ABSORB'],15:['POISON POWDER'],17:['STUN SPORE'],19:['SLEEP POWDER'],24:['ACID'],33:['PETAL DANCE'],46:['SOLAR BEAM']}),
    44:('GLOOM',['GRASS','POISON'],[60,65,70,85,75,40],132,120,None,45,{1:['ABSORB','POISON POWDER','STUN SPORE'],19:['SLEEP POWDER'],28:['ACID'],38:['PETAL DANCE'],52:['SOLAR BEAM']}),
    45:('VILEPLUME',['GRASS','POISON'],[75,80,85,110,90,50],184,45,None,None,{1:['STUN SPORE','SLEEP POWDER','ACID','PETAL DANCE']}),
    46:('PARAS',['BUG','GRASS'],[35,70,55,45,55,25],70,190,24,47,{1:['SCRATCH'],13:['STUN SPORE'],20:['LEECH LIFE'],27:['SPORE'],34:['SLASH'],41:['GROWTH']}),
    47:('PARASECT',['BUG','GRASS'],[60,95,80,60,80,30],128,75,None,None,{1:['SCRATCH','STUN SPORE','LEECH LIFE'],30:['SPORE'],39:['SLASH'],48:['GROWTH']}),
    48:('VENONAT',['BUG','POISON'],[60,55,50,40,55,45],75,190,31,49,{1:['TACKLE','DISABLE'],24:['POISON POWDER'],27:['LEECH LIFE'],30:['STUN SPORE'],35:['PSYBEAM'],38:['SLEEP POWDER'],43:['PSYCHIC']}),
    49:('VENOMOTH',['BUG','POISON'],[70,65,60,90,75,90],138,75,None,None,{1:['TACKLE','DISABLE','POISON POWDER','LEECH LIFE'],38:['PSYBEAM'],43:['SLEEP POWDER'],50:['PSYCHIC']}),
    50:('DIGLETT',['GROUND'],[10,55,25,35,45,95],81,255,26,51,{1:['SCRATCH'],15:['GROWL'],19:['DIG'],24:['SAND ATTACK'],31:['SLASH'],40:['EARTHQUAKE']}),
    51:('DUGTRIO',['GROUND'],[35,100,50,50,70,120],153,50,None,None,{1:['SCRATCH','GROWL','DIG'],24:['SAND ATTACK'],35:['SLASH'],47:['EARTHQUAKE']}),
    52:('MEOWTH',['NORMAL'],[40,45,35,40,40,90],69,255,28,53,{1:['SCRATCH','GROWL'],12:['BITE'],17:['PAY DAY'],24:['SCREECH'],33:['FURY SWIPES'],44:['SLASH']}),
    53:('PERSIAN',['NORMAL'],[65,70,60,65,65,115],148,90,None,None,{1:['SCRATCH','GROWL','BITE','SCREECH'],37:['FURY SWIPES'],51:['SLASH']}),
    54:('PSYDUCK',['WATER'],[50,52,48,65,50,55],80,190,33,55,{1:['SCRATCH'],28:['TAIL WHIP'],31:['DISABLE'],36:['CONFUSION'],43:['FURY SWIPES'],52:['HYDRO PUMP']}),
    55:('GOLDUCK',['WATER'],[80,82,78,95,80,85],174,75,None,None,{1:['SCRATCH','TAIL WHIP','DISABLE'],39:['CONFUSION'],48:['FURY SWIPES'],59:['HYDRO PUMP']}),
    56:('MANKEY',['FIGHTING'],[40,80,35,35,45,70],74,190,28,57,{1:['SCRATCH','LEER'],15:['KARATE CHOP'],21:['FURY SWIPES'],27:['FOCUS ENERGY'],33:['SEISMIC TOSS'],39:['THRASH']}),
    57:('PRIMEAPE',['FIGHTING'],[65,105,60,60,70,95],149,75,None,None,{1:['SCRATCH','LEER','KARATE CHOP','FURY SWIPES'],28:['FOCUS ENERGY'],37:['SEISMIC TOSS'],46:['THRASH']}),
    58:('GROWLITHE',['FIRE'],[55,70,45,70,50,60],91,190,None,59,{1:['BITE','ROAR'],18:['EMBER'],23:['LEER'],30:['TAKE DOWN'],39:['AGILITY'],50:['FLAMETHROWER']}),
    59:('ARCANINE',['FIRE'],[90,110,80,100,80,95],213,75,None,None,{1:['ROAR','EMBER','LEER','TAKE DOWN']}),
    60:('POLIWAG',['WATER'],[40,50,40,40,40,90],77,255,25,61,{1:['BUBBLE'],16:['HYPNOSIS'],19:['WATER GUN'],25:['DOUBLE SLAP'],31:['BODY SLAM'],38:['AMNESIA'],45:['HYDRO PUMP']}),
    61:('POLIWHIRL',['WATER'],[65,65,65,50,50,90],131,120,None,62,{1:['BUBBLE','HYPNOSIS','WATER GUN'],26:['DOUBLE SLAP'],33:['BODY SLAM'],41:['AMNESIA'],49:['HYDRO PUMP']}),
    62:('POLIWRATH',['WATER','FIGHTING'],[90,95,95,70,90,70],185,45,None,None,{1:['HYPNOSIS','WATER GUN','DOUBLE SLAP','BODY SLAM']}),
    63:('ABRA',['PSYCHIC'],[25,20,15,105,55,90],73,200,16,64,{1:['TELEPORT']}),
    64:('KADABRA',['PSYCHIC'],[40,35,30,120,70,105],145,100,None,65,{1:['TELEPORT','CONFUSION','DISABLE'],20:['CONFUSION'],27:['PSYBEAM'],31:['RECOVER'],38:['PSYCHIC'],42:['REFLECT']}),
    65:('ALAKAZAM',['PSYCHIC'],[55,50,45,135,95,120],186,50,None,None,{1:['TELEPORT','CONFUSION','DISABLE'],20:['CONFUSION'],27:['PSYBEAM'],31:['RECOVER'],38:['PSYCHIC'],42:['REFLECT']}),
    66:('MACHOP',['FIGHTING'],[70,80,50,35,35,35],75,180,28,67,{1:['KARATE CHOP'],20:['LOW KICK'],25:['LEER'],32:['FOCUS ENERGY'],39:['SEISMIC TOSS'],46:['SUBMISSION']}),
    67:('MACHOKE',['FIGHTING'],[80,100,70,50,60,45],146,90,None,68,{1:['KARATE CHOP','LOW KICK','LEER'],36:['FOCUS ENERGY'],44:['SEISMIC TOSS'],52:['SUBMISSION']}),
    68:('MACHAMP',['FIGHTING'],[90,130,80,65,85,55],193,45,None,None,{1:['KARATE CHOP','LOW KICK','LEER'],36:['FOCUS ENERGY'],44:['SEISMIC TOSS'],52:['SUBMISSION']}),
    69:('BELLSPROUT',['GRASS','POISON'],[50,75,35,70,30,40],84,255,21,70,{1:['VINE WHIP','GROWTH'],13:['WRAP'],15:['POISON POWDER'],18:['SLEEP POWDER'],21:['STUN SPORE'],26:['ACID'],33:['RAZOR LEAF'],42:['SLAM']}),
    70:('WEEPINBELL',['GRASS','POISON'],[65,90,50,85,45,55],151,120,None,71,{1:['VINE WHIP','GROWTH','WRAP'],15:['POISON POWDER'],18:['SLEEP POWDER'],23:['STUN SPORE'],29:['ACID'],38:['RAZOR LEAF'],49:['SLAM']}),
    71:('VICTREEBEL',['GRASS','POISON'],[80,105,65,100,70,70],191,45,None,None,{1:['SLEEP POWDER','STUN SPORE','ACID','RAZOR LEAF']}),
    72:('TENTACOOL',['WATER','POISON'],[40,40,35,50,100,70],105,190,30,73,{1:['ACID'],7:['SUPERSONIC'],13:['WRAP'],18:['POISON STING'],22:['WATER GUN'],27:['CONSTRICT'],33:['BARRIER'],40:['SCREECH'],48:['HYDRO PUMP']}),
    73:('TENTACRUEL',['WATER','POISON'],[80,70,65,80,120,100],205,60,None,None,{1:['ACID','SUPERSONIC','WRAP'],18:['POISON STING'],22:['WATER GUN'],35:['BARRIER'],43:['SCREECH'],50:['HYDRO PUMP']}),
    74:('GEODUDE',['ROCK','GROUND'],[40,80,100,30,30,20],73,255,25,75,{1:['TACKLE'],11:['DEFENSE CURL'],16:['ROCK THROW'],21:['SELFDESTRUCT'],26:['HARDEN'],31:['EARTHQUAKE'],36:['EXPLOSION']}),
    75:('GRAVELER',['ROCK','GROUND'],[55,95,115,45,45,35],134,120,None,76,{1:['TACKLE','DEFENSE CURL'],16:['ROCK THROW'],21:['SELFDESTRUCT'],29:['HARDEN'],36:['EARTHQUAKE'],43:['EXPLOSION']}),
    76:('GOLEM',['ROCK','GROUND'],[80,120,130,55,65,45],177,45,None,None,{1:['TACKLE','DEFENSE CURL','ROCK THROW'],21:['SELFDESTRUCT'],29:['HARDEN'],36:['EARTHQUAKE'],43:['EXPLOSION']}),
    77:('PONYTA',['FIRE'],[50,85,55,65,65,90],152,190,40,78,{1:['EMBER'],30:['TAIL WHIP'],32:['STOMP'],35:['GROWL'],39:['FIRE SPIN'],43:['TAKE DOWN'],48:['AGILITY']}),
    78:('RAPIDASH',['FIRE'],[65,100,70,80,80,105],192,60,None,None,{1:['EMBER','TAIL WHIP','STOMP','GROWL'],39:['FIRE SPIN'],47:['TAKE DOWN'],55:['AGILITY']}),
    79:('SLOWPOKE',['WATER','PSYCHIC'],[90,65,65,40,40,15],99,190,37,80,{1:['CONFUSION'],18:['DISABLE'],22:['HEADBUTT'],27:['GROWL'],33:['WATER GUN'],40:['AMNESIA'],48:['PSYCHIC']}),
    80:('SLOWBRO',['WATER','PSYCHIC'],[95,75,110,100,80,30],164,75,None,None,{1:['CONFUSION','DISABLE','HEADBUTT'],27:['GROWL'],33:['WATER GUN'],37:['WITHDRAW'],44:['AMNESIA'],55:['PSYCHIC']}),
    81:('MAGNEMITE',['ELECTRIC'],[25,35,70,95,55,45],89,190,30,82,{1:['TACKLE'],21:['SONIC BOOM'],25:['THUNDERSHOCK'],29:['SUPERSONIC'],35:['THUNDER WAVE'],41:['SWIFT'],47:['SCREECH']}),
    82:('MAGNETON',['ELECTRIC'],[50,60,95,120,70,70],161,60,None,None,{1:['TACKLE','SONIC BOOM','THUNDERSHOCK'],29:['SUPERSONIC'],38:['THUNDER WAVE'],46:['SWIFT'],54:['SCREECH']}),
    83:('FARFETCHD',['NORMAL','FLYING'],[52,90,55,58,62,60],94,45,None,None,{1:['PECK','SAND ATTACK'],7:['LEER'],15:['FURY ATTACK'],23:['SWORDS DANCE'],31:['AGILITY'],39:['SLASH']}),
    84:('DODUO',['NORMAL','FLYING'],[35,85,45,35,35,75],96,190,31,85,{1:['PECK'],20:['GROWL'],24:['FURY ATTACK'],30:['DRILL PECK'],36:['RAGE'],40:['TRI ATTACK'],44:['AGILITY']}),
    85:('DODRIO',['NORMAL','FLYING'],[60,110,70,60,60,110],158,45,None,None,{1:['PECK','GROWL','FURY ATTACK'],30:['DRILL PECK'],39:['RAGE'],45:['TRI ATTACK'],51:['AGILITY']}),
    86:('SEEL',['WATER'],[65,45,55,45,70,45],100,190,34,87,{1:['HEADBUTT'],30:['GROWL'],35:['AURORA BEAM'],40:['REST'],45:['TAKE DOWN'],50:['ICE BEAM']}),
    87:('DEWGONG',['WATER','ICE'],[90,70,80,70,95,70],176,75,None,None,{1:['HEADBUTT','GROWL','AURORA BEAM'],35:['REST'],44:['TAKE DOWN'],50:['ICE BEAM']}),
    88:('GRIMER',['POISON'],[80,80,50,40,50,25],90,190,38,89,{1:['POUND','DISABLE'],30:['POISON GAS'],33:['MINIMIZE'],37:['SLUDGE'],42:['HARDEN'],48:['SCREECH'],55:['ACID ARMOR']}),
    89:('MUK',['POISON'],[105,105,75,65,100,50],157,75,None,None,{1:['POUND','DISABLE','POISON GAS'],33:['MINIMIZE'],37:['SLUDGE'],45:['HARDEN'],53:['SCREECH'],60:['ACID ARMOR']}),
    90:('SHELLDER',['WATER'],[30,65,100,45,25,40],97,190,None,91,{1:['TACKLE','WITHDRAW'],18:['SUPERSONIC'],23:['CLAMP'],30:['AURORA BEAM'],39:['LEER'],50:['ICE BEAM']}),
    91:('CLOYSTER',['WATER','ICE'],[50,95,180,85,45,70],203,60,None,None,{1:['WITHDRAW','SUPERSONIC','CLAMP','AURORA BEAM']}),
    92:('GASTLY',['GHOST','POISON'],[30,35,30,100,35,80],95,190,25,93,{1:['LICK','CONFUSE RAY','NIGHT SHADE'],27:['HYPNOSIS'],35:['DREAM EATER']}),
    93:('HAUNTER',['GHOST','POISON'],[45,50,45,115,55,95],126,90,None,94,{1:['LICK','CONFUSE RAY','NIGHT SHADE'],29:['HYPNOSIS'],38:['DREAM EATER']}),
    94:('GENGAR',['GHOST','POISON'],[60,65,60,130,75,110],190,45,None,None,{1:['LICK','CONFUSE RAY','NIGHT SHADE'],29:['HYPNOSIS'],38:['DREAM EATER']}),
    95:('ONIX',['ROCK','GROUND'],[35,45,160,30,45,70],108,45,None,None,{1:['TACKLE','SCREECH'],15:['BIND'],19:['ROCK THROW'],25:['RAGE'],33:['SLAM'],43:['HARDEN']}),
    96:('DROWZEE',['PSYCHIC'],[60,48,45,43,90,42],102,190,26,97,{1:['POUND','HYPNOSIS'],12:['DISABLE'],17:['CONFUSION'],24:['HEADBUTT'],29:['POISON GAS'],32:['PSYCHIC'],37:['MEDITATE']}),
    97:('HYPNO',['PSYCHIC'],[85,73,70,73,115,67],165,75,None,None,{1:['POUND','HYPNOSIS','DISABLE','CONFUSION'],33:['HEADBUTT'],37:['POISON GAS'],43:['PSYCHIC'],49:['MEDITATE']}),
    98:('KRABBY',['WATER'],[30,105,90,25,25,50],115,225,28,99,{1:['BUBBLE','LEER'],20:['VICE GRIP'],25:['GUILLOTINE'],30:['STOMP'],35:['CRABHAMMER'],40:['HARDEN']}),
    99:('KINGLER',['WATER'],[55,130,115,50,50,75],206,60,None,None,{1:['BUBBLE','LEER','VICE GRIP'],25:['GUILLOTINE'],34:['STOMP'],42:['CRABHAMMER'],49:['HARDEN']}),
    100:('VOLTORB',['ELECTRIC'],[40,30,50,55,55,100],103,190,30,101,{1:['TACKLE','SCREECH'],17:['SONIC BOOM'],22:['SELFDESTRUCT'],29:['LIGHT SCREEN'],36:['SWIFT'],43:['EXPLOSION']}),
    101:('ELECTRODE',['ELECTRIC'],[60,50,70,80,80,150],150,60,None,None,{1:['TACKLE','SCREECH','SONIC BOOM'],22:['SELFDESTRUCT'],29:['LIGHT SCREEN'],40:['SWIFT'],50:['EXPLOSION']}),
    102:('EXEGGCUTE',['GRASS','PSYCHIC'],[60,40,80,60,45,40],98,90,None,103,{1:['BARRAGE','HYPNOSIS'],25:['REFLECT'],28:['LEECH SEED'],32:['STUN SPORE'],37:['POISON POWDER'],42:['SOLAR BEAM'],48:['SLEEP POWDER']}),
    103:('EXEGGUTOR',['GRASS','PSYCHIC'],[95,95,85,125,75,55],212,45,None,None,{1:['BARRAGE','HYPNOSIS','STOMP']}),
    104:('CUBONE',['GROUND'],[50,50,95,40,50,35],87,190,28,105,{1:['BONE CLUB','GROWL'],25:['LEER'],31:['FOCUS ENERGY'],38:['THRASH'],43:['BONEMERANG'],46:['RAGE']}),
    105:('MAROWAK',['GROUND'],[60,80,110,50,80,45],124,75,None,None,{1:['BONE CLUB','GROWL','LEER','FOCUS ENERGY'],41:['THRASH'],48:['BONEMERANG'],55:['RAGE']}),
    106:('HITMONLEE',['FIGHTING'],[50,120,53,35,110,87],139,45,None,None,{1:['DOUBLE KICK','MEDITATE'],33:['ROLLING KICK'],38:['JUMP KICK'],43:['FOCUS ENERGY'],48:['HI JUMP KICK'],53:['MEGA KICK']}),
    107:('HITMONCHAN',['FIGHTING'],[50,105,79,35,110,76],140,45,None,None,{1:['COMET PUNCH','AGILITY'],33:['FIRE PUNCH'],38:['ICE PUNCH'],43:['THUNDER PUNCH'],48:['MEGA PUNCH'],53:['COUNTER']}),
    108:('LICKITUNG',['NORMAL'],[90,55,75,60,75,30],127,45,None,None,{1:['WRAP','SUPERSONIC'],7:['STOMP'],15:['DISABLE'],23:['DEFENSE CURL'],31:['SLAM'],39:['SCREECH']}),
    109:('KOFFING',['POISON'],[40,65,95,60,45,35],114,190,35,110,{1:['TACKLE','SMOG'],32:['SLUDGE'],37:['SMOKESCREEN'],40:['SELFDESTRUCT'],45:['HAZE'],48:['EXPLOSION']}),
    110:('WEEZING',['POISON'],[65,90,120,85,70,60],173,60,None,None,{1:['TACKLE','SMOG','SLUDGE'],39:['SMOKESCREEN'],43:['SELFDESTRUCT'],49:['HAZE'],53:['EXPLOSION']}),
    111:('RHYHORN',['GROUND','ROCK'],[80,85,95,30,30,25],135,120,42,112,{1:['HORN ATTACK'],30:['STOMP'],35:['TAIL WHIP'],40:['FURY ATTACK'],45:['HORN DRILL'],50:['LEER'],55:['TAKE DOWN']}),
    112:('RHYDON',['GROUND','ROCK'],[105,130,120,45,45,40],204,60,None,None,{1:['HORN ATTACK','STOMP','TAIL WHIP','FURY ATTACK'],48:['HORN DRILL'],55:['LEER'],64:['TAKE DOWN']}),
    113:('CHANSEY',['NORMAL'],[250,5,5,35,105,50],255,30,None,None,{1:['POUND','DOUBLE SLAP'],24:['SING'],30:['GROWL'],38:['MINIMIZE'],44:['DEFENSE CURL'],48:['LIGHT SCREEN'],54:['DOUBLE-EDGE']}),
    114:('TANGELA',['GRASS'],[65,55,115,100,40,60],166,45,None,None,{1:['CONSTRICT','BIND'],29:['ABSORB'],32:['POISON POWDER'],36:['STUN SPORE'],39:['SLEEP POWDER'],45:['SLAM'],49:['GROWTH']}),
    115:('KANGASKHAN',['NORMAL'],[105,95,80,40,80,90],175,45,None,None,{1:['COMET PUNCH','RAGE'],26:['BITE'],31:['TAIL WHIP'],36:['MEGA PUNCH'],41:['LEER'],46:['DIZZY PUNCH']}),
    116:('HORSEA',['WATER'],[30,40,70,70,25,60],83,225,32,117,{1:['BUBBLE'],19:['SMOKESCREEN'],24:['LEER'],30:['WATER GUN'],37:['AGILITY'],45:['HYDRO PUMP']}),
    117:('SEADRA',['WATER'],[55,65,95,95,45,85],155,75,None,None,{1:['BUBBLE','SMOKESCREEN'],24:['LEER'],30:['WATER GUN'],41:['AGILITY'],52:['HYDRO PUMP']}),
    118:('GOLDEEN',['WATER'],[45,67,60,35,50,63],111,225,33,119,{1:['PECK','TAIL WHIP'],19:['SUPERSONIC'],24:['HORN ATTACK'],30:['FURY ATTACK'],37:['WATERFALL'],45:['HORN DRILL'],54:['AGILITY']}),
    119:('SEAKING',['WATER'],[80,92,65,65,80,68],170,60,None,None,{1:['PECK','TAIL WHIP','SUPERSONIC'],24:['HORN ATTACK'],30:['FURY ATTACK'],39:['WATERFALL'],48:['HORN DRILL'],54:['AGILITY']}),
    120:('STARYU',['WATER'],[30,45,55,70,55,85],106,225,None,121,{1:['TACKLE'],17:['WATER GUN'],22:['HARDEN'],27:['RECOVER'],32:['SWIFT'],37:['MINIMIZE'],42:['LIGHT SCREEN'],47:['HYDRO PUMP']}),
    121:('STARMIE',['WATER','PSYCHIC'],[60,75,85,100,85,115],207,60,None,None,{1:['TACKLE','WATER GUN','HARDEN']}),
    122:('MR. MIME',['PSYCHIC'],[40,45,65,100,120,90],136,45,None,None,{1:['CONFUSION','BARRIER'],15:['CONFUSION'],23:['LIGHT SCREEN'],31:['DOUBLE SLAP'],39:['MEDITATE'],47:['SUBSTITUTE']}),
    123:('SCYTHER',['BUG','FLYING'],[70,110,80,55,80,105],187,45,None,None,{1:['QUICK ATTACK'],17:['LEER'],20:['FOCUS ENERGY'],24:['DOUBLE TEAM'],29:['SLASH'],35:['SWORDS DANCE'],42:['AGILITY']}),
    124:('JYNX',['ICE','PSYCHIC'],[65,50,35,115,95,95],137,45,None,None,{1:['POUND','LOVELY KISS'],18:['LICK'],23:['DOUBLE SLAP'],31:['ICE PUNCH'],39:['BODY SLAM'],47:['THRASH'],58:['BLIZZARD']}),
    125:('ELECTABUZZ',['ELECTRIC'],[65,83,57,95,85,105],156,45,None,None,{1:['QUICK ATTACK','LEER'],34:['THUNDERSHOCK'],37:['SCREECH'],42:['THUNDER PUNCH'],49:['LIGHT SCREEN'],54:['THUNDER']}),
    126:('MAGMAR',['FIRE'],[65,95,57,100,85,93],167,45,None,None,{1:['EMBER'],36:['LEER'],39:['CONFUSE RAY'],43:['FIRE PUNCH'],48:['SMOKESCREEN'],52:['SMOG'],55:['FLAMETHROWER']}),
    127:('PINSIR',['BUG'],[65,125,100,55,70,85],200,45,None,None,{1:['VICE GRIP'],25:['SEISMIC TOSS'],30:['GUILLOTINE'],36:['FOCUS ENERGY'],43:['HARDEN'],49:['SLASH'],54:['SWORDS DANCE']}),
    128:('TAUROS',['NORMAL'],[75,100,95,40,70,110],211,45,None,None,{1:['TACKLE'],21:['STOMP'],28:['TAIL WHIP'],35:['LEER'],44:['RAGE'],51:['TAKE DOWN']}),
    129:('MAGIKARP',['WATER'],[20,10,55,15,20,80],20,255,20,130,{1:['SPLASH'],15:['TACKLE']}),
    130:('GYARADOS',['WATER','FLYING'],[95,125,79,60,100,81],214,45,None,None,{1:['BITE','DRAGON RAGE','LEER','HYDRO PUMP'],20:['BITE'],25:['DRAGON RAGE'],32:['LEER'],41:['HYDRO PUMP'],52:['HYPER BEAM']}),
    131:('LAPRAS',['WATER','ICE'],[130,85,80,85,95,60],219,45,None,None,{1:['WATER GUN','GROWL'],16:['SING'],20:['MIST'],25:['BODY SLAM'],31:['CONFUSE RAY'],38:['ICE BEAM'],46:['HYDRO PUMP']}),
    132:('DITTO',['NORMAL'],[48,48,48,48,48,48],61,35,None,None,{1:['TRANSFORM']}),
    133:('EEVEE',['NORMAL'],[55,55,50,45,65,55],92,45,None,None,{1:['TACKLE','SAND ATTACK'],27:['QUICK ATTACK'],31:['TAIL WHIP'],37:['BITE'],45:['TAKE DOWN']}),
    134:('VAPOREON',['WATER'],[130,65,60,110,95,65],196,45,None,None,{1:['TACKLE','SAND ATTACK','QUICK ATTACK','WATER GUN'],31:['TAIL WHIP'],37:['BITE'],40:['ACID ARMOR'],44:['HAZE'],48:['MIST'],54:['HYDRO PUMP']}),
    135:('JOLTEON',['ELECTRIC'],[65,65,60,110,95,130],197,45,None,None,{1:['TACKLE','SAND ATTACK','QUICK ATTACK','THUNDERSHOCK'],31:['TAIL WHIP'],37:['THUNDER WAVE'],40:['DOUBLE KICK'],44:['AGILITY'],48:['PIN MISSILE'],54:['THUNDER']}),
    136:('FLAREON',['FIRE'],[65,130,60,95,110,65],198,45,None,None,{1:['TACKLE','SAND ATTACK','QUICK ATTACK','EMBER'],31:['TAIL WHIP'],37:['BITE'],40:['LEER'],44:['FIRE SPIN'],48:['RAGE'],54:['FLAMETHROWER']}),
    137:('PORYGON',['NORMAL'],[65,60,70,85,75,40],130,45,None,None,{1:['TACKLE','SHARPEN'],23:['PSYBEAM'],28:['RECOVER'],35:['AGILITY'],42:['TRI ATTACK']}),
    138:('OMANYTE',['ROCK','WATER'],[35,40,100,90,55,35],120,45,40,139,{1:['WATER GUN','WITHDRAW'],34:['HORN ATTACK'],39:['LEER'],46:['SPIKE CANNON'],53:['HYDRO PUMP']}),
    139:('OMASTAR',['ROCK','WATER'],[70,60,125,115,70,55],199,45,None,None,{1:['WATER GUN','WITHDRAW','HORN ATTACK'],39:['LEER'],44:['SPIKE CANNON'],49:['HYDRO PUMP']}),
    140:('KABUTO',['ROCK','WATER'],[30,80,90,55,45,55],119,45,40,141,{1:['SCRATCH','HARDEN'],34:['ABSORB'],39:['SLASH'],44:['LEER'],49:['HYDRO PUMP']}),
    141:('KABUTOPS',['ROCK','WATER'],[60,115,105,65,70,80],201,45,None,None,{1:['SCRATCH','HARDEN','ABSORB'],39:['SLASH'],46:['LEER'],53:['HYDRO PUMP']}),
    142:('AERODACTYL',['ROCK','FLYING'],[80,105,65,60,75,130],202,45,None,None,{1:['WING ATTACK','AGILITY'],33:['SUPERSONIC'],38:['BITE'],45:['TAKE DOWN'],54:['HYPER BEAM']}),
    143:('SNORLAX',['NORMAL'],[160,110,65,65,110,30],154,25,None,None,{1:['HEADBUTT','AMNESIA','REST'],35:['BODY SLAM'],41:['HARDEN'],48:['DOUBLE-EDGE'],56:['HYPER BEAM']}),
    144:('ARTICUNO',['ICE','FLYING'],[90,85,100,95,125,85],215,3,None,None,{1:['PECK','ICE BEAM'],51:['BLIZZARD'],55:['AGILITY'],60:['MIST']}),
    145:('ZAPDOS',['ELECTRIC','FLYING'],[90,90,85,125,90,100],216,3,None,None,{1:['PECK','THUNDERSHOCK'],51:['DRILL PECK'],55:['THUNDER'],60:['AGILITY'],65:['LIGHT SCREEN']}),
    146:('MOLTRES',['FIRE','FLYING'],[90,100,90,125,85,90],217,3,None,None,{1:['PECK','FIRE SPIN'],51:['LEER'],55:['AGILITY'],60:['SKY ATTACK']}),
    147:('DRATINI',['DRAGON'],[41,64,45,50,50,50],67,45,30,148,{1:['WRAP','LEER'],10:['THUNDER WAVE'],20:['AGILITY'],30:['SLAM'],40:['DRAGON RAGE'],50:['HYPER BEAM']}),
    148:('DRAGONAIR',['DRAGON'],[61,84,65,70,70,70],144,45,55,149,{1:['WRAP','LEER','THUNDER WAVE'],20:['AGILITY'],35:['SLAM'],45:['DRAGON RAGE'],55:['HYPER BEAM']}),
    149:('DRAGONITE',['DRAGON','FLYING'],[91,134,95,100,100,80],218,45,None,None,{1:['WRAP','LEER','THUNDER WAVE','AGILITY'],35:['SLAM'],45:['DRAGON RAGE'],55:['HYPER BEAM']}),
    150:('MEWTWO',['PSYCHIC'],[106,110,90,154,90,130],220,3,None,None,{1:['CONFUSION','DISABLE','SWIFT','PSYCHIC'],63:['BARRIER'],66:['PSYCHIC'],70:['RECOVER'],75:['MIST'],81:['AMNESIA']}),
    151:('MEW',['PSYCHIC'],[100,100,100,100,100,100],64,45,None,None,{1:['POUND'],10:['TRANSFORM'],20:['MEGA PUNCH'],30:['METRONOME'],40:['PSYCHIC']}),
}

# ═══════════════════════════════════════════════════════════════════════════════
# ITEMS
# ═══════════════════════════════════════════════════════════════════════════════
ITEMS = {
    'POKE BALL':{'type':'ball','rate':1.0,'price':200},'GREAT BALL':{'type':'ball','rate':1.5,'price':600},
    'ULTRA BALL':{'type':'ball','rate':2.0,'price':1200},'MASTER BALL':{'type':'ball','rate':255,'price':0},
    'POTION':{'type':'heal','hp':20,'price':300},'SUPER POTION':{'type':'heal','hp':50,'price':700},
    'HYPER POTION':{'type':'heal','hp':200,'price':1200},'MAX POTION':{'type':'heal','hp':999,'price':2500},
    'FULL RESTORE':{'type':'full','price':3000},'REVIVE':{'type':'revive','pct':0.5,'price':1500},
    'MAX REVIVE':{'type':'revive','pct':1.0,'price':4000},'ANTIDOTE':{'type':'status','cure':'PSN','price':100},
    'BURN HEAL':{'type':'status','cure':'BRN','price':250},'ICE HEAL':{'type':'status','cure':'FRZ','price':250},
    'AWAKENING':{'type':'status','cure':'SLP','price':250},'PARALYZ HEAL':{'type':'status','cure':'PAR','price':200},
    'FULL HEAL':{'type':'status','cure':'ALL','price':600},'RARE CANDY':{'type':'lvlup','price':0},
    'ESCAPE ROPE':{'type':'escape','price':550},'REPEL':{'type':'repel','steps':100,'price':350},
    'TOWN MAP':{'type':'key','price':0},'POKEDEX':{'type':'key','price':0},'BICYCLE':{'type':'key','price':0},
    'OLD ROD':{'type':'rod','price':0},'GOOD ROD':{'type':'rod','price':0},'SUPER ROD':{'type':'rod','price':0},
}

# ═══════════════════════════════════════════════════════════════════════════════
# GYM LEADERS
# ═══════════════════════════════════════════════════════════════════════════════
GYM_LEADERS = {
    'BROCK':{'badge':'BOULDER','type':'ROCK','prize':1386,'team':[(74,12),(95,14)]},
    'MISTY':{'badge':'CASCADE','type':'WATER','prize':2100,'team':[(120,18),(121,21)]},
    'LT. SURGE':{'badge':'THUNDER','type':'ELECTRIC','prize':2100,'team':[(100,21),(25,18),(26,24)]},
    'ERIKA':{'badge':'RAINBOW','type':'GRASS','prize':2871,'team':[(71,29),(114,24),(44,29)]},
    'KOGA':{'badge':'SOUL','type':'POISON','prize':4455,'team':[(109,37),(89,39),(109,37),(110,43)]},
    'SABRINA':{'badge':'MARSH','type':'PSYCHIC','prize':4257,'team':[(64,38),(122,37),(49,38),(65,43)]},
    'BLAINE':{'badge':'VOLCANO','type':'FIRE','prize':5346,'team':[(58,42),(77,40),(78,42),(59,47)]},
    'GIOVANNI':{'badge':'EARTH','type':'GROUND','prize':5643,'team':[(111,45),(51,42),(31,44),(34,45),(112,50)]},
}

# ═══════════════════════════════════════════════════════════════════════════════
# TILES
# ═══════════════════════════════════════════════════════════════════════════════
TILES = {
    '.':('GRASS',GREEN,True,False),'~':('TALL',( 0,120,0),True,True),'#':('WALL',DARK,False,False),
    'T':('TREE',(34,139,34),False,False),'W':('WATER',BLUE,False,False),'P':('PATH',(200,180,160),True,False),
    'F':('FLOOR',(180,160,140),True,False),'D':('DOOR',BROWN,True,False),'C':('PC',RED,True,False),
    'M':('MART',BLUE,True,False),'G':('GYM',ORANGE,True,False),'H':('HOUSE',PURPLE,True,False),
    'E':('EXIT',GREEN,True,False),'B':('CAVE',(60,60,80),True,False),'S':('SIGN',(139,90,43),False,False),
    'L':('LEDGE',BROWN,True,False),'^':('STUP',GRAY,True,False),'v':('STDN',GRAY,True,False),'@':('START',GREEN,True,False),
}

# ═══════════════════════════════════════════════════════════════════════════════
# MAPS - Complete Kanto
# ═══════════════════════════════════════════════════════════════════════════════
MAPS = {
    'PALLET_TOWN':{'name':'PALLET TOWN','w':20,'h':18,'data':[
        "TTTTTTTTTTTTTTTTTTTT","T..................T","T.TTTT....TTTT.....T","T.T##T....T##T.....T",
        "T.THHT....TCCT.....T","T..................T","T......PPPP........T","T......PPPP........T",
        "T..................T","T.TTTT.....TTTT....T","T.T##T.....T##T....T","T.THHT.....THHT....T",
        "T..................T","T...~~~~~..........T","T...~~~~~..........T","T..................T",
        "EEEEPPPPPPPPPPPPEEEE","TTTTTTTTTTTTTTTTTTTT"],
        'conn':{'n':('ROUTE_1',10,29)},'enc':{'grass':[(16,3),(19,3)],'rate':5}},
    'ROUTE_1':{'name':'ROUTE 1','w':20,'h':30,'data':[
        "EEEEPPPPPPPPPPPPEEEE","T~~~PPPP....PPPP~~~T","T~~~PPPP....PPPP~~~T","T...PPPP....PPPP...T",
        "T...PPPPPPPPPPPP...T","T...PPPPPPPPPPPP...T","T~~~....PPPP....~~~T","T~~~....PPPP....~~~T",
        "T.......PPPP.......T","T.......PPPP.......T","T~~~....PPPP....~~~T","T~~~PPPPPPPP....~~~T",
        "T...PPPPPPPP.......T","T...PPPP...........T","T...PPPP~~~........T","T~~~PPPP~~~........T",
        "T~~~PPPP...........T","T...PPPP.......~~~~T","T...PPPPPPPP...~~~~T","T...PPPPPPPP.......T",
        "T~~~....PPPP.......T","T~~~....PPPP~~~....T","T.......PPPP~~~....T","T.......PPPP.......T",
        "T~~~....PPPP....~~~T","T~~~....PPPP....~~~T","T...PPPPPPPP....~~~T","T...PPPPPPPP.......T",
        "T~~~....PPPP.......T","EEEEPPPPPPPPPPPPEEEE"],
        'conn':{'s':('PALLET_TOWN',10,0),'n':('VIRIDIAN_CITY',10,19)},'enc':{'grass':[(16,3),(19,4)],'rate':20}},
    'VIRIDIAN_CITY':{'name':'VIRIDIAN CITY','w':25,'h':22,'data':[
        "TTTTTTTTTTTTTTTTTTTTTTTTT","T.......................T","T..TTTTTTT...TTTTTTT....T","T..T#####T...T#####T....T",
        "T..TMMMMMT...THHHHHT....T","T.......................T","T.....PPPPPPPPPP........T","T.....PPPPPPPPPP........T",
        "T..TTTTTTTPPPPTTTTTTT...T","T..T#####TPPPPT#####T...T","T..TCCCCCTPPPPTGGGGGT...T","T.........PPPP..........T",
        "T.........PPPP..........T","T~~~~.....PPPP.....~~~~~T","T~~~~PPPPPPPPPPPPP~~~~~ET","T....PPPPPPPPPPPPP......T",
        "T....PPPP.....PPPP......T","T~~~~PPPP.....PPPP...~~~T","T~~~~PPPP.....PPPP...~~~T","EEEEPPPP.......PPPPEEEET",
        "T......................ET","TTTTTTTTTTTTTTTTTTTTTTTTT"],
        'conn':{'s':('ROUTE_1',10,0),'n':('ROUTE_2',10,39),'w':('ROUTE_22',24,8)},'gym':'GIOVANNI'},
    'ROUTE_2':{'name':'ROUTE 2','w':20,'h':40,'data':[
        "EEEEPPPPPPPPPPPPEEEE","T...PPPP....PPPP...T","T~~~PPPP....PPPP~~~T","T~~~PPPP....PPPP~~~T",
        "T...PPPPPPPPPPPP...T","T..TTTTTPPPPTTTTT..T","T..TBBBBTPPPPTBBBT.T","T.......PPPP.......T",
        "T~~~....PPPP....~~~T","T~~~....PPPP....~~~T","T.......PPPP.......T","T...PPPPPPPPPPPP...T",
        "T...PPPPPPPPPPPP...T","T~~~....PPPP....~~~T","T~~~....PPPP....~~~T","T.......PPPP.......T",
        "T.......PPPP.......T","T~~~....PPPP....~~~T","T~~~PPPPPPPP....~~~T","T...PPPPPPPP.......T",
        "T...PPPP...........T","T...PPPP~~~........T","T~~~PPPP~~~........T","T~~~PPPP...........T",
        "T...PPPP.......~~~~T","T...PPPPPPPP...~~~~T","T...PPPPPPPP.......T","T~~~....PPPP.......T",
        "T~~~....PPPP~~~....T","T.......PPPP~~~....T","T.......PPPP.......T","T~~~....PPPP....~~~T",
        "T~~~....PPPP....~~~T","T...PPPPPPPP....~~~T","T...PPPPPPPP.......T","T~~~....PPPP.......T",
        "T~~~....PPPP~~~....T","T.......PPPP~~~....T","T.......PPPP.......T","EEEEPPPPPPPPPPPPEEEE"],
        'conn':{'s':('VIRIDIAN_CITY',10,0),'n':('PEWTER_CITY',10,21)},'enc':{'grass':[(10,4),(13,4)],'rate':20}},
    'PEWTER_CITY':{'name':'PEWTER CITY','w':25,'h':24,'data':[
        "TTTTTTTTTTTTTTTTTTTTTTTTT","T.......................T","T..TTTTTTT...TTTTTTT....T","T..T#####T...T#####T....T",
        "T..TMMMMMT...THHHHHT....T","T.......................T","T.....PPPPPPPPPP........T","T.....PPPPPPPPPP........T",
        "T..TTTTTTTPPPPTTTTTTT...T","T..T#####TPPPPT#####T...T","T..TCCCCCTPPPPTGGGGGT...T","T.........PPPP..........T",
        "T.........PPPP..........T","T..TTTTTTTPPPPTTTTTT....T","T..T#####TPPPPT####T....T","T..THHHHHTPPPPTHHHHT....T",
        "T.........PPPP..........T","T.........PPPP..........T","T~~~~.....PPPP.....~~~~~T","T~~~~PPPPPPPPPPPPP~~~~~ET",
        "T....PPPPPPPPPPPPP......T","EEEEPPPPPP...PPPPPPEEEET","T......................ET","TTTTTTTTTTTTTTTTTTTTTTTTT"],
        'conn':{'s':('ROUTE_2',10,0),'e':('ROUTE_3',0,8)},'gym':'BROCK'},
    'ROUTE_3':{'name':'ROUTE 3','w':45,'h':15,'data':[
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT","T...........................................T",
        "T~~~....PPPPPPPPPPPPPPPPPPPPPPPP....~~~~...ET","T~~~....PPPPPPPPPPPPPPPPPPPPPPPP....~~~~....T",
        "T.......PPPP....................PPPPPPPP....T","T.......PPPP....................PPPPPPPP....T",
        "T~~~....PPPP....~~~....~~~......PPPP...~~~~~T","T~~~PPPPPPPP....~~~....~~~......PPPP...~~~~~T",
        "EPPPPPPPP...............................PPPPE","T.......................................PPPPT",
        "T~~~....PPPPPPPPPPPP....PPPPPPPPPPPP....PPPPT","T~~~....PPPPPPPPPPPP....PPPPPPPPPPPP........T",
        "T.......PPPP........~~~~PPPP................T","T.......PPPP........~~~~PPPP................T",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"],
        'conn':{'w':('PEWTER_CITY',24,8),'e':('MT_MOON',0,6)},'enc':{'grass':[(21,6),(16,6)],'rate':20}},
    'MT_MOON':{'name':'MT. MOON','w':30,'h':20,'data':[
        "##############################","#............................#","#.######################.....#","#.#....................#.....#",
        "#.#.FFFFFFFFFFFFFFFF...#.....#","#.#.F..............F...#.....#","#E#.F......^^......F...#.....#","#.#.FFFFFFFFFFFFFFFF...#.....#",
        "#.#....................#.....#","#.######################.....#","#............................#","#.######################.....#",
        "#.#....................#.....#","#.#.FFFFFFFFFFFFFFFF...#.....#","#.#.F......vv......F...#.....#","#.#.F..............F...#.....#",
        "#.#.FFFFFFFFFFFFFFFF...#....E#","#.#....................#.....#","#.######################.....#","##############################"],
        'enc':{'grass':[(41,15),(74,12)],'rate':15}},
    'CERULEAN_CITY':{'name':'CERULEAN CITY','w':25,'h':22,'data':[
        "TTTTTTTTTTTTTTTTTTTTTTTTT","T.......................T","T..TTTTTTT...TTTTTTT....T","T..T#####T...T#####T....T",
        "T..TMMMMMT...THHHHHT....T","T.......................T","T.....PPPPPPPPPP........T","T.....PPPPPPPPPP........T",
        "T..TTTTTTTPPPPTTTTTTT...T","T..T#####TPPPPT#####T...T","T..TCCCCCTPPPPTGGGGGT...T","T.........PPPP..........T",
        "T.........PPPP..........T","T~~~~.....PPPP.....~~~~~T","T~~~~PPPPPPPPPPPPP~~~~~ET","T....PPPPPPPPPPPPP......T",
        "T....PPPP.....PPPP......T","EWWWWPPPP.....PPPP...WWWE","EWWWWPPPP.....PPPP...WWWE","EEEEPPPPP.....PPPPPEEEEET",
        "T......................ET","TTTTTTTTTTTTTTTTTTTTTTTTT"],
        'conn':{'s':('ROUTE_5',10,0),'n':('ROUTE_24',10,29),'w':('ROUTE_4',39,8)},'gym':'MISTY'},
    'INDIGO_PLATEAU':{'name':'INDIGO PLATEAU','w':20,'h':20,'data':[
        "TTTTTTTTTTTTTTTTTTTT","T..................T","T..TTTTTTTTTTTTTT..T","T..T############T..T",
        "T..THHHHHHHHHHHT...T","T..................T","T......PPPPPP......T","T......PPPPPP......T",
        "T......PPPPPP......T","T......PPPPPP......T","T..TTTTTPPPPTTTTT..T","T..T###TPPPPT###T..T",
        "T..THHTPPPPPTHHT...T","T......PPPPPP......T","T......PPPPPP......T","T..................T",
        "T..................T","EEEEPPPPPPPPPPEEEEET","T..................T","TTTTTTTTTTTTTTTTTTTT"],
        'elite_four':True},
}

# ═══════════════════════════════════════════════════════════════════════════════
# POKEMON CLASS
# ═══════════════════════════════════════════════════════════════════════════════
class Pokemon:
    def __init__(self, dex, lvl, nick=None):
        d = POKEMON.get(dex, POKEMON[1])
        self.dex, self.lvl = dex, lvl
        self.name = nick or d[0]
        self.species, self.types = d[0], d[1]
        self.base = d[2]
        self.ivs = [random.randint(0,15) for _ in range(6)]
        self.evs = [0]*6
        self.calc_stats()
        self.hp = self.maxhp
        self.moves, self.pp, self.maxpp = [], [], []
        for lv in sorted(d[7].keys()):
            if lv <= lvl:
                for m in d[7][lv]:
                    if m in MOVES:
                        if len(self.moves) < 4:
                            self.moves.append(m)
                            self.pp.append(MOVES[m][3])
                            self.maxpp.append(MOVES[m][3])
                        else:
                            i = random.randint(0,3)
                            self.moves[i], self.pp[i], self.maxpp[i] = m, MOVES[m][3], MOVES[m][3]
        self.status = None
        self.stages = {s:0 for s in ['ATK','DEF','SPA','SPD','SPE','ACC','EVA']}
        self.exp = lvl**3
    
    def calc_stats(self):
        self.maxhp = int(((self.base[0]+self.ivs[0])*2+self.evs[0]**0.5/4)*self.lvl/100)+self.lvl+10
        for i,s in enumerate(['atk','def_','spa','spd','spe']):
            setattr(self,s,int(((self.base[i+1]+self.ivs[i+1])*2+self.evs[i+1]**0.5/4)*self.lvl/100)+5)
    
    def get_stat(self,s):
        base = getattr(self,s.lower().replace('def','def_').replace('spd','spd').replace('spa','spa').replace('spe','spe'),self.atk)
        st = self.stages.get(s,0)
        return int(base*(2+st)/2) if st>=0 else int(base*2/(2-st))
    
    def gain_exp(self,amt):
        self.exp += amt
        lv = False
        while self.exp >= (self.lvl+1)**3 and self.lvl<100:
            self.lvl += 1
            old = self.maxhp
            self.calc_stats()
            self.hp += self.maxhp - old
            lv = True
            d = POKEMON[self.dex]
            if d[5] and self.lvl >= d[5]:
                self.evolve()
        return lv
    
    def evolve(self):
        d = POKEMON[self.dex]
        if d[6]:
            self.dex = d[6]
            nd = POKEMON[self.dex]
            if self.name == d[0]: self.name = nd[0]
            self.species, self.types, self.base = nd[0], nd[1], nd[2]
            self.calc_stats()
    
    def heal(self):
        self.hp, self.status = self.maxhp, None
        for i in range(len(self.pp)): self.pp[i] = self.maxpp[i]
    
    def fainted(self): return self.hp <= 0
    
    def to_dict(self):
        return {'dex':self.dex,'lvl':self.lvl,'name':self.name,'hp':self.hp,'exp':self.exp,
                'ivs':self.ivs,'evs':self.evs,'moves':self.moves,'pp':self.pp,'maxpp':self.maxpp,'status':self.status}
    
    @classmethod
    def from_dict(cls, d):
        p = cls(d['dex'], d['lvl'], d.get('name'))
        p.hp, p.exp = d.get('hp',p.maxhp), d.get('exp',p.exp)
        p.ivs, p.evs = d.get('ivs',p.ivs), d.get('evs',p.evs)
        p.moves, p.pp, p.maxpp = d.get('moves',p.moves), d.get('pp',p.pp), d.get('maxpp',p.maxpp)
        p.status = d.get('status')
        p.calc_stats()
        return p

# ═══════════════════════════════════════════════════════════════════════════════
# SAVE SYSTEM
# ═══════════════════════════════════════════════════════════════════════════════
SAVE_FILE = os.path.expanduser("~/.cats_pokered_save.json")

def save_game(G):
    data = {
        'ver':'0.1','time':datetime.now().isoformat(),
        'player':{'name':G.name,'rival':G.rival,'money':G.money,'badges':list(G.badges),'flags':list(G.flags)},
        'pos':{'map':G.map_id,'x':G.x,'y':G.y,'face':G.face},
        'party':[p.to_dict() for p in G.party],
        'pc':[[p.to_dict() for p in b] for b in G.pc],
        'bag':dict(G.bag),
        'dex':{'seen':list(G.seen),'caught':list(G.caught)},
        'playtime':G.playtime
    }
    data['hash'] = hashlib.md5(json.dumps(data,sort_keys=True).encode()).hexdigest()
    try:
        with open(SAVE_FILE,'w') as f: json.dump(data,f,indent=2)
        return True
    except: return False

def load_game():
    try:
        with open(SAVE_FILE,'r') as f: return json.load(f)
    except: return None

def delete_save():
    try: os.remove(SAVE_FILE); return True
    except: return False

# ═══════════════════════════════════════════════════════════════════════════════
# GAME STATE
# ═══════════════════════════════════════════════════════════════════════════════
class Game:
    def __init__(self):
        self.reset()
    
    def reset(self):
        self.name, self.rival = "RED", "BLUE"
        self.money = 3000
        self.map_id, self.x, self.y, self.face = 'PALLET_TOWN', 10, 14, 'down'
        self.party, self.pc = [], [[] for _ in range(12)]
        self.seen, self.caught = set(), set()
        self.bag = {'POKE BALL':5,'POTION':3,'TOWN MAP':1,'POKEDEX':1}
        self.badges, self.flags = set(), set()
        self.state, self.frame, self.playtime = 'TITLE', 0, 0
        self.battle, self.menu, self.dialog = None, [], []
        self.menu_sel, self.dialog_idx = 0, 0
    
    def apply_save(self, d):
        p = d.get('player',{})
        self.name, self.rival = p.get('name','RED'), p.get('rival','BLUE')
        self.money = p.get('money',3000)
        self.badges, self.flags = set(p.get('badges',[])), set(p.get('flags',[]))
        pos = d.get('pos',{})
        self.map_id, self.x, self.y, self.face = pos.get('map','PALLET_TOWN'), pos.get('x',10), pos.get('y',14), pos.get('face','down')
        self.party = [Pokemon.from_dict(x) for x in d.get('party',[])]
        self.pc = [[Pokemon.from_dict(x) for x in b] for b in d.get('pc',[[] for _ in range(12)])]
        self.bag = d.get('bag',{'POKE BALL':5,'POTION':3})
        dex = d.get('dex',{})
        self.seen, self.caught = set(dex.get('seen',[])), set(dex.get('caught',[]))
        self.playtime = d.get('playtime',0)
        self.state = 'OVERWORLD'

G = Game()

# ═══════════════════════════════════════════════════════════════════════════════
# AUDIO
# ═══════════════════════════════════════════════════════════════════════════════
RATE = 22050
def pulse(f, d, duty=0.5, v=0.12):
    if f==0: return [0.0]*int(RATE*d)
    s, per = [], RATE/f
    for i in range(int(RATE*d)): s.append(v if (i%per)/per<duty else -v)
    return s

def mksnd(s):
    i = [int(max(-32767,min(32767,x*32767))) for x in s]
    st = []
    for x in i: st.extend([x,x])
    return pygame.mixer.Sound(buffer=array.array('h',st))

SFX = {
    'sel':mksnd(pulse(800,0.05)+pulse(1000,0.05)),
    'mov':mksnd(pulse(600,0.03)),
    'bump':mksnd(pulse(200,0.05)),
    'hit':mksnd(pulse(200,0.08)+pulse(150,0.08)),
    'lvl':mksnd(pulse(523,0.1)+pulse(659,0.1)+pulse(784,0.2)),
    'heal':mksnd(pulse(400,0.1)+pulse(500,0.1)+pulse(600,0.1)+pulse(800,0.2)),
    'catch':mksnd(pulse(300,0.15)+pulse(400,0.15)+pulse(600,0.3)),
}

# ═══════════════════════════════════════════════════════════════════════════════
# RENDERING
# ═══════════════════════════════════════════════════════════════════════════════
TILE = 16

def draw_tile(s, t, x, y):
    if t in TILES:
        _,c,_,_ = TILES[t]
        pygame.draw.rect(s, c, (x,y,TILE,TILE))
        if t=='T':
            pygame.draw.circle(s,(0,80,0),(x+8,y+6),5)
            pygame.draw.rect(s,BROWN,(x+6,y+10,4,6))
        elif t=='~':
            for i in range(3): pygame.draw.line(s,(0,150,0),(x+2,y+4+i*4),(x+14,y+4+i*4),2)
        elif t=='W':
            pygame.draw.line(s,(150,200,255),(x+2,y+6),(x+14,y+6),2)
            pygame.draw.line(s,(150,200,255),(x+2,y+10),(x+14,y+10),2)
    else:
        pygame.draw.rect(s,BLACK,(x,y,TILE,TILE))

def draw_player(s, x, y, f, fr):
    pygame.draw.rect(s,RED,(x+4,y,8,6))
    pygame.draw.rect(s,(255,200,160),(x+4,y+6,8,6))
    pygame.draw.rect(s,BLUE,(x+2,y+12,12,8))
    if f=='down': pygame.draw.rect(s,BLACK,(x+5,y+8,2,2)); pygame.draw.rect(s,BLACK,(x+9,y+8,2,2))
    elif f=='up': pygame.draw.rect(s,BLACK,(x+4,y+2,8,4))
    elif f=='left': pygame.draw.rect(s,BLACK,(x+4,y+8,2,2))
    elif f=='right': pygame.draw.rect(s,BLACK,(x+10,y+8,2,2))

def draw_pkmn(s, dex, x, y, sc=1):
    if dex not in POKEMON: return
    c = TYPE_COLORS.get(POKEMON[dex][1][0], GRAY)
    sz = 24*sc
    pygame.draw.ellipse(s,c,(x,y,sz,sz))
    pygame.draw.ellipse(s,WHITE,(x+sz//4,y+sz//4,sz//4,sz//4))
    pygame.draw.circle(s,BLACK,(x+sz//4+sz//8,y+sz//4+sz//8),2*sc)

def draw_map(s, mid):
    if mid not in MAPS: return
    m = MAPS[mid]
    d = m['data']
    cx, cy = G.x - GB_W//TILE//2, G.y - GB_H//TILE//2
    for sy in range(GB_H//TILE+2):
        for sx in range(GB_W//TILE+2):
            mx, my = cx+sx, cy+sy
            if 0<=my<len(d) and 0<=mx<len(d[0]):
                draw_tile(s, d[my][mx], sx*TILE, sy*TILE)
    draw_player(s, GB_W//2-8, GB_H//2-10, G.face, G.frame)

def draw_text(s, t, x, y, c=BLACK):
    f = pygame.font.Font(None, 14)
    s.blit(f.render(str(t),True,c),(x,y))

def draw_box(s, x, y, w, h, c=WHITE):
    pygame.draw.rect(s,c,(x,y,w,h))
    pygame.draw.rect(s,BLACK,(x,y,w,h),2)

def draw_hp(s, x, y, w, cur, mx):
    r = cur/mx if mx>0 else 0
    bw = int((w-4)*r)
    pygame.draw.rect(s,BLACK,(x,y,w,6))
    pygame.draw.rect(s,WHITE,(x+1,y+1,w-2,4))
    c = GREEN if r>0.5 else YELLOW if r>0.2 else RED
    if bw>0: pygame.draw.rect(s,c,(x+2,y+2,bw,2))

# ═══════════════════════════════════════════════════════════════════════════════
# BATTLE
# ═══════════════════════════════════════════════════════════════════════════════
class Battle:
    def __init__(self, wild=None, trainer=None, tname=None):
        self.player = G.party[0] if G.party else None
        self.enemy = wild
        self.trainer, self.tname = trainer, tname
        self.tparty, self.tidx = [], 0
        self.wild = trainer is None
        if trainer:
            self.tparty = [Pokemon(d,l) for d,l in trainer]
            self.enemy = self.tparty[0]
        self.state, self.midx, self.mvidx = 'INTRO', 0, 0
        self.msg, self.msgidx = [], 0
        self.prize = 0
    
    def start(self):
        if self.wild: self.msg = [f"Wild {self.enemy.name} appeared!"]
        else: self.msg = [f"{self.tname} wants to fight!", f"{self.tname} sent out {self.enemy.name}!"]
        self.state = 'INTRO'
    
    def input(self, k):
        if self.state in ['INTRO','MSG','RES']:
            if k in [pygame.K_SPACE, pygame.K_RETURN, pygame.K_z]:
                self.msgidx += 1
                if self.msgidx >= len(self.msg):
                    if self.state=='INTRO': self.state='MENU'
                    elif self.state=='RES': return self.check_end()
                    else:
                        r = self.check_end()
                        if r: return r
                    self.msg, self.msgidx = [], 0
        elif self.state == 'MENU':
            if k==pygame.K_UP: self.midx=(self.midx-2)%4; SFX['mov'].play()
            elif k==pygame.K_DOWN: self.midx=(self.midx+2)%4; SFX['mov'].play()
            elif k==pygame.K_LEFT: self.midx=(self.midx-1)%4; SFX['mov'].play()
            elif k==pygame.K_RIGHT: self.midx=(self.midx+1)%4; SFX['mov'].play()
            elif k in [pygame.K_SPACE, pygame.K_RETURN, pygame.K_z]:
                SFX['sel'].play()
                if self.midx==0: self.state='MOVE'; self.mvidx=0
                elif self.midx==1: self.try_catch()
                elif self.midx==3:
                    if self.try_run(): return 'RUN'
        elif self.state == 'MOVE':
            mm = len(self.player.moves)
            if k==pygame.K_UP: self.mvidx=(self.mvidx-2)%mm; SFX['mov'].play()
            elif k==pygame.K_DOWN: self.mvidx=(self.mvidx+2)%mm; SFX['mov'].play()
            elif k==pygame.K_LEFT: self.mvidx=(self.mvidx-1)%mm; SFX['mov'].play()
            elif k==pygame.K_RIGHT: self.mvidx=(self.mvidx+1)%mm; SFX['mov'].play()
            elif k in [pygame.K_SPACE, pygame.K_RETURN, pygame.K_z]:
                SFX['sel'].play()
                self.do_turn(self.player.moves[self.mvidx])
            elif k in [pygame.K_ESCAPE, pygame.K_x]:
                self.state='MENU'; SFX['sel'].play()
        return None
    
    def do_turn(self, pm):
        ps, es = self.player.get_stat('SPE'), self.enemy.get_stat('SPE')
        em = random.choice(self.enemy.moves) if self.enemy.moves else 'TACKLE'
        self.msg = []
        if ps >= es:
            self.do_move(self.player, self.enemy, pm, True)
            if not self.enemy.fainted(): self.do_move(self.enemy, self.player, em, False)
        else:
            self.do_move(self.enemy, self.player, em, False)
            if not self.player.fainted(): self.do_move(self.player, self.enemy, pm, True)
        self.state, self.msgidx = 'MSG', 0
    
    def do_move(self, atk, df, mv, isp):
        if mv not in MOVES: return
        m = MOVES[mv]
        mtype, pwr, acc, pp, cat, eff = m
        pf = atk.name if isp else f"Foe {atk.name}"
        self.msg.append(f"{pf} used {mv}!")
        if random.randint(1,100) > acc:
            self.msg.append("But it missed!")
            return
        if pwr > 0:
            a = atk.get_stat('ATK' if cat=='PHY' else 'SPA')
            d = df.get_stat('DEF' if cat=='PHY' else 'SPD')
            eff_m = type_eff(mtype, df.types)
            stab = 1.5 if mtype in atk.types else 1.0
            rnd = random.randint(85,100)/100
            dmg = int(((2*atk.lvl/5+2)*pwr*a/d/50+2)*stab*eff_m*rnd)
            dmg = max(1, dmg)
            df.hp = max(0, df.hp - dmg)
            SFX['hit'].play()
            if eff_m > 1: self.msg.append("Super effective!")
            elif 0 < eff_m < 1: self.msg.append("Not very effective...")
            elif eff_m == 0: self.msg.append("It had no effect...")
    
    def try_run(self):
        if not self.wild:
            self.msg, self.state = ["Can't run!"], 'MSG'
            return False
        if random.randint(0,255) < (self.player.spe*32)//(self.enemy.spe//4+1)+30:
            return True
        self.msg, self.state = ["Can't escape!"], 'MSG'
        return False
    
    def try_catch(self):
        if not self.wild:
            self.msg, self.state = ["Can't catch trainer's Pokemon!"], 'MSG'
            return
        if G.bag.get('POKE BALL',0) <= 0:
            self.msg, self.state = ["No Poke Balls!"], 'MSG'
            return
        G.bag['POKE BALL'] -= 1
        self.msg = ["You threw a POKE BALL!"]
        cr = POKEMON[self.enemy.dex][4]
        hpf = (3*self.enemy.maxhp - 2*self.enemy.hp) / (3*self.enemy.maxhp)
        cv = cr * hpf
        if random.randint(0,255) < cv:
            self.msg.append(f"Gotcha! {self.enemy.name} was caught!")
            SFX['catch'].play()
            if len(G.party) < 6: G.party.append(self.enemy)
            else:
                G.pc[0].append(self.enemy)
                self.msg.append(f"{self.enemy.name} sent to PC!")
            G.caught.add(self.enemy.dex)
            self.state = 'WIN'
        else:
            self.msg.append("Oh no! It broke free!")
        self.state = 'MSG'
    
    def check_end(self):
        if self.state == 'WIN': return 'WIN'
        if self.enemy.fainted():
            exp = (self.enemy.lvl * POKEMON[self.enemy.dex][3]) // 7
            lv = self.player.gain_exp(exp)
            self.msg = [f"{self.enemy.name} fainted!", f"{self.player.name} gained {exp} EXP!"]
            if lv:
                self.msg.append(f"{self.player.name} grew to Lv.{self.player.lvl}!")
                SFX['lvl'].play()
            if self.trainer and self.tidx < len(self.tparty)-1:
                self.tidx += 1
                self.enemy = self.tparty[self.tidx]
                self.msg.append(f"{self.tname} sent out {self.enemy.name}!")
                self.state = 'MSG'
                return None
            self.state = 'WIN'
            return None
        if self.player.fainted():
            self.msg = [f"{self.player.name} fainted!"]
            alive = [p for p in G.party if not p.fainted()]
            if not alive:
                self.msg.append("You blacked out!")
                self.state = 'LOSE'
            else:
                for i,p in enumerate(G.party):
                    if not p.fainted():
                        G.party[0], G.party[i] = G.party[i], G.party[0]
                        self.player = G.party[0]
                        self.msg.append(f"Go! {self.player.name}!")
                        self.state = 'MSG'
                        break
            return None
        self.state = 'MENU'
        return None
    
    def draw(self, s):
        s.fill(WHITE)
        if self.enemy:
            draw_pkmn(s, self.enemy.dex, 100, 20, 2)
            draw_box(s, 5, 10, 75, 32)
            draw_text(s, self.enemy.name[:10], 8, 12)
            draw_text(s, f"Lv{self.enemy.lvl}", 8, 22)
            draw_hp(s, 8, 32, 65, self.enemy.hp, self.enemy.maxhp)
        if self.player:
            draw_pkmn(s, self.player.dex, 20, 60, 2)
            draw_box(s, 80, 70, 75, 42)
            draw_text(s, self.player.name[:10], 83, 72)
            draw_text(s, f"Lv{self.player.lvl}", 83, 82)
            draw_hp(s, 83, 92, 65, self.player.hp, self.player.maxhp)
            draw_text(s, f"{self.player.hp}/{self.player.maxhp}", 83, 102)
        draw_box(s, 0, 118, GB_W, 26)
        if self.msg and self.msgidx < len(self.msg):
            draw_text(s, self.msg[self.msgidx], 8, 124)
        elif self.state == 'MENU':
            for i,o in enumerate(['FIGHT','BAG','PKMN','RUN']):
                x, y = 85+(i%2)*38, 120+(i//2)*12
                draw_text(s, ('>' if i==self.midx else ' ')+o, x, y)
        elif self.state == 'MOVE':
            draw_box(s, 0, 95, GB_W, 49)
            for i,m in enumerate(self.player.moves[:4]):
                x, y = 5+(i%2)*78, 100+(i//2)*12
                draw_text(s, ('>' if i==self.mvidx else ' ')+m[:12], x, y)

# ═══════════════════════════════════════════════════════════════════════════════
# SCREENS
# ═══════════════════════════════════════════════════════════════════════════════
def draw_title(s):
    s.fill((200,0,0))
    f = pygame.font.Font(None, 24)
    s.blit(f.render("CAT'S",True,WHITE),(GB_W//2-25,20))
    s.blit(f.render("POKERED",True,YELLOW),(GB_W//2-35,45))
    f2 = pygame.font.Font(None, 16)
    s.blit(f2.render("VERSION 0.1",True,WHITE),(GB_W//2-35,70))
    draw_pkmn(s, 6, GB_W//2-24, 85, 2)
    if G.frame % 60 < 40:
        s.blit(f2.render("PRESS SPACE",True,WHITE),(GB_W//2-35,128))

def draw_menu(s):
    draw_map(s, G.map_id)
    draw_box(s, GB_W-70, 10, 65, 90)
    opts = ['POKEMON','BAG','SAVE','LOAD','EXIT']
    for i,o in enumerate(opts):
        draw_text(s, ('>' if i==G.menu_sel else ' ')+o, GB_W-65, 15+i*16)

def draw_save_msg(s, msg):
    draw_map(s, G.map_id)
    draw_box(s, 20, 50, 120, 44)
    draw_text(s, msg, 30, 65)

# ═══════════════════════════════════════════════════════════════════════════════
# MOVEMENT
# ═══════════════════════════════════════════════════════════════════════════════
def can_walk(mid, x, y):
    if mid not in MAPS: return False
    m = MAPS[mid]
    d = m['data']
    if y<0 or y>=len(d) or x<0 or x>=len(d[0]): return False
    t = d[y][x]
    return TILES.get(t,(None,None,False,False))[2]

def check_enc(mid, x, y):
    if mid not in MAPS: return None
    m = MAPS[mid]
    d = m['data']
    if y<0 or y>=len(d) or x<0 or x>=len(d[0]): return None
    t = d[y][x]
    if not TILES.get(t,(None,None,False,False))[3]: return None
    enc = m.get('enc',{})
    rate = enc.get('rate',0)
    if random.randint(1,100) <= rate:
        gr = enc.get('grass',[])
        if gr:
            dex, lvl = random.choice(gr)
            lvl = max(2, lvl + random.randint(-2,2))
            return Pokemon(dex, lvl)
    return None

def check_conn(mid, x, y):
    if mid not in MAPS: return None
    m = MAPS[mid]
    d = m['data']
    conn = m.get('conn',{})
    if y<=0 and 'n' in conn: return conn['n']
    if y>=len(d)-1 and 's' in conn: return conn['s']
    if x<=0 and 'w' in conn: return conn['w']
    if x>=len(d[0])-1 and 'e' in conn: return conn['e']
    return None

# ═══════════════════════════════════════════════════════════════════════════════
# NEW GAME
# ═══════════════════════════════════════════════════════════════════════════════
def new_game():
    G.reset()
    starter = Pokemon(4, 5)  # Charmander Lv5
    G.party.append(starter)
    G.seen.add(4)
    G.caught.add(4)
    G.state = 'OVERWORLD'

# ═══════════════════════════════════════════════════════════════════════════════
# MAIN LOOP
# ═══════════════════════════════════════════════════════════════════════════════
def main():
    running = True
    cooldown = 0
    save_msg, save_timer = "", 0
    
    while running:
        for ev in pygame.event.get():
            if ev.type == pygame.QUIT:
                running = False
            elif ev.type == pygame.KEYDOWN:
                if G.state == 'TITLE':
                    if ev.key == pygame.K_SPACE:
                        SFX['sel'].play()
                        sd = load_game()
                        if sd:
                            G.apply_save(sd)
                        else:
                            new_game()
                elif G.state == 'OVERWORLD':
                    if ev.key in [pygame.K_ESCAPE, pygame.K_RETURN]:
                        G.state = 'MENU'
                        G.menu_sel = 0
                        SFX['sel'].play()
                elif G.state == 'MENU':
                    if ev.key == pygame.K_ESCAPE:
                        G.state = 'OVERWORLD'
                        SFX['sel'].play()
                    elif ev.key == pygame.K_UP:
                        G.menu_sel = (G.menu_sel - 1) % 5
                        SFX['mov'].play()
                    elif ev.key == pygame.K_DOWN:
                        G.menu_sel = (G.menu_sel + 1) % 5
                        SFX['mov'].play()
                    elif ev.key in [pygame.K_SPACE, pygame.K_RETURN, pygame.K_z]:
                        SFX['sel'].play()
                        if G.menu_sel == 2:  # SAVE
                            if save_game(G):
                                save_msg, save_timer = "GAME SAVED!", 120
                            else:
                                save_msg, save_timer = "SAVE FAILED!", 120
                            G.state = 'SAVE_MSG'
                        elif G.menu_sel == 3:  # LOAD
                            sd = load_game()
                            if sd:
                                G.apply_save(sd)
                                save_msg, save_timer = "GAME LOADED!", 120
                            else:
                                save_msg, save_timer = "NO SAVE FILE!", 120
                            G.state = 'SAVE_MSG'
                        elif G.menu_sel == 4:  # EXIT
                            G.state = 'OVERWORLD'
                elif G.state == 'SAVE_MSG':
                    if ev.key in [pygame.K_SPACE, pygame.K_RETURN, pygame.K_z]:
                        G.state = 'OVERWORLD'
                        save_timer = 0
                elif G.state == 'BATTLE':
                    r = G.battle.input(ev.key)
                    if r == 'RUN':
                        G.state = 'OVERWORLD'
                        G.battle = None
                    elif G.battle and G.battle.state == 'WIN':
                        G.state = 'OVERWORLD'
                        G.battle = None
                    elif G.battle and G.battle.state == 'LOSE':
                        for p in G.party: p.heal()
                        G.map_id, G.x, G.y = 'PALLET_TOWN', 10, 14
                        G.state = 'OVERWORLD'
                        G.battle = None
        
        # Movement
        if G.state == 'OVERWORLD' and cooldown == 0:
            keys = pygame.key.get_pressed()
            dx, dy = 0, 0
            if keys[pygame.K_UP]: dy, G.face = -1, 'up'
            elif keys[pygame.K_DOWN]: dy, G.face = 1, 'down'
            elif keys[pygame.K_LEFT]: dx, G.face = -1, 'left'
            elif keys[pygame.K_RIGHT]: dx, G.face = 1, 'right'
            if dx or dy:
                nx, ny = G.x+dx, G.y+dy
                conn = check_conn(G.map_id, nx, ny)
                if conn:
                    G.map_id, G.x, G.y = conn
                    cooldown = 8
                elif can_walk(G.map_id, nx, ny):
                    G.x, G.y = nx, ny
                    cooldown = 8
                    wild = check_enc(G.map_id, G.x, G.y)
                    if wild:
                        G.seen.add(wild.dex)
                        G.battle = Battle(wild)
                        G.battle.start()
                        G.state = 'BATTLE'
                else:
                    SFX['bump'].play()
                    cooldown = 8
        
        if cooldown > 0: cooldown -= 1
        if save_timer > 0:
            save_timer -= 1
            if save_timer == 0 and G.state == 'SAVE_MSG':
                G.state = 'OVERWORLD'
        
        G.frame += 1
        G.playtime += 1
        
        # Draw
        gb.fill(WHITE)
        if G.state == 'TITLE': draw_title(gb)
        elif G.state == 'OVERWORLD': draw_map(gb, G.map_id)
        elif G.state == 'MENU': draw_menu(gb)
        elif G.state == 'SAVE_MSG': draw_save_msg(gb, save_msg)
        elif G.state == 'BATTLE' and G.battle: G.battle.draw(gb)
        
        pygame.transform.scale(gb, (WIDTH, HEIGHT), screen)
        pygame.display.flip()
        clock.tick(60)
    
    pygame.quit()

if __name__ == "__main__":
    print("╔═══════════════════════════════════════════════════╗")
    print("║        CAT'S POKERED 0.1 - Team Flames            ║")
    print("╠═══════════════════════════════════════════════════╣")
    print("║  Controls:                                        ║")
    print("║    Arrow Keys - Move                              ║")
    print("║    Z / Space  - Confirm                           ║")
    print("║    X / Esc    - Cancel / Menu                     ║")
    print("║    Enter      - Menu                              ║")
    print("╠═══════════════════════════════════════════════════╣")
    print("║  Save Location: ~/.cats_pokered_save.json         ║")
    print("╚═══════════════════════════════════════════════════╝")
    main()
